// Code generated by protoc-gen-go.
// source: ticket.proto
// DO NOT EDIT!

/*
Package ticket is a generated protocol buffer package.

It is generated from these files:
	ticket.proto

It has these top-level messages:
	AccountRequest
	AccountReply
	LoginRequest
	LoginReply
	HareRequest
	HareReply
	PasswordRequest
	TicketDetails
	RecordReply
	TicketStats
	StatsReply
	PullLocRequest
	PullPerformanceRequest
	PullAnchorRequest
	PullTicketStatsRequest
	PullTicketRequest
	SlaveLoc
	SlavePerformance
	MasterOrder
	SlaveAnchors
	TicketRange
	TicketRangeReply
	TicketRangeSid
*/
package ticket

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AccountRequest struct {
	UserId         string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Password       string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	PoliceName     string `protobuf:"bytes,3,opt,name=police_name,json=policeName" json:"police_name,omitempty"`
	PoliceType     string `protobuf:"bytes,4,opt,name=police_type,json=policeType" json:"police_type,omitempty"`
	PoliceCity     string `protobuf:"bytes,5,opt,name=police_city,json=policeCity" json:"police_city,omitempty"`
	PoliceDept     string `protobuf:"bytes,6,opt,name=police_dept,json=policeDept" json:"police_dept,omitempty"`
	PoliceSquad    string `protobuf:"bytes,7,opt,name=police_squad,json=policeSquad" json:"police_squad,omitempty"`
	PoliceSection  string `protobuf:"bytes,8,opt,name=police_section,json=policeSection" json:"police_section,omitempty"`
	PolicePortrait []byte `protobuf:"bytes,9,opt,name=police_portrait,json=policePortrait,proto3" json:"police_portrait,omitempty"`
}

func (m *AccountRequest) Reset()                    { *m = AccountRequest{} }
func (m *AccountRequest) String() string            { return proto.CompactTextString(m) }
func (*AccountRequest) ProtoMessage()               {}
func (*AccountRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AccountRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *AccountRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AccountRequest) GetPoliceName() string {
	if m != nil {
		return m.PoliceName
	}
	return ""
}

func (m *AccountRequest) GetPoliceType() string {
	if m != nil {
		return m.PoliceType
	}
	return ""
}

func (m *AccountRequest) GetPoliceCity() string {
	if m != nil {
		return m.PoliceCity
	}
	return ""
}

func (m *AccountRequest) GetPoliceDept() string {
	if m != nil {
		return m.PoliceDept
	}
	return ""
}

func (m *AccountRequest) GetPoliceSquad() string {
	if m != nil {
		return m.PoliceSquad
	}
	return ""
}

func (m *AccountRequest) GetPoliceSection() string {
	if m != nil {
		return m.PoliceSection
	}
	return ""
}

func (m *AccountRequest) GetPolicePortrait() []byte {
	if m != nil {
		return m.PolicePortrait
	}
	return nil
}

type AccountReply struct {
	CreateSuccess bool `protobuf:"varint,1,opt,name=create_success,json=createSuccess" json:"create_success,omitempty"`
}

func (m *AccountReply) Reset()                    { *m = AccountReply{} }
func (m *AccountReply) String() string            { return proto.CompactTextString(m) }
func (*AccountReply) ProtoMessage()               {}
func (*AccountReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AccountReply) GetCreateSuccess() bool {
	if m != nil {
		return m.CreateSuccess
	}
	return false
}

type LoginRequest struct {
	UserId   string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *LoginRequest) Reset()                    { *m = LoginRequest{} }
func (m *LoginRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()               {}
func (*LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *LoginRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginReply struct {
	LoginSuccess   bool   `protobuf:"varint,1,opt,name=login_success,json=loginSuccess" json:"login_success,omitempty"`
	PoliceName     string `protobuf:"bytes,2,opt,name=police_name,json=policeName" json:"police_name,omitempty"`
	PoliceType     string `protobuf:"bytes,3,opt,name=police_type,json=policeType" json:"police_type,omitempty"`
	PoliceCity     string `protobuf:"bytes,4,opt,name=police_city,json=policeCity" json:"police_city,omitempty"`
	PoliceDept     string `protobuf:"bytes,5,opt,name=police_dept,json=policeDept" json:"police_dept,omitempty"`
	PoliceSquad    string `protobuf:"bytes,6,opt,name=police_squad,json=policeSquad" json:"police_squad,omitempty"`
	PoliceSection  string `protobuf:"bytes,7,opt,name=police_section,json=policeSection" json:"police_section,omitempty"`
	PolicePortrait []byte `protobuf:"bytes,8,opt,name=police_portrait,json=policePortrait,proto3" json:"police_portrait,omitempty"`
}

func (m *LoginReply) Reset()                    { *m = LoginReply{} }
func (m *LoginReply) String() string            { return proto.CompactTextString(m) }
func (*LoginReply) ProtoMessage()               {}
func (*LoginReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *LoginReply) GetLoginSuccess() bool {
	if m != nil {
		return m.LoginSuccess
	}
	return false
}

func (m *LoginReply) GetPoliceName() string {
	if m != nil {
		return m.PoliceName
	}
	return ""
}

func (m *LoginReply) GetPoliceType() string {
	if m != nil {
		return m.PoliceType
	}
	return ""
}

func (m *LoginReply) GetPoliceCity() string {
	if m != nil {
		return m.PoliceCity
	}
	return ""
}

func (m *LoginReply) GetPoliceDept() string {
	if m != nil {
		return m.PoliceDept
	}
	return ""
}

func (m *LoginReply) GetPoliceSquad() string {
	if m != nil {
		return m.PoliceSquad
	}
	return ""
}

func (m *LoginReply) GetPoliceSection() string {
	if m != nil {
		return m.PoliceSection
	}
	return ""
}

func (m *LoginReply) GetPolicePortrait() []byte {
	if m != nil {
		return m.PolicePortrait
	}
	return nil
}

type HareRequest struct {
	Sid string `protobuf:"bytes,1,opt,name=sid" json:"sid,omitempty"`
}

func (m *HareRequest) Reset()                    { *m = HareRequest{} }
func (m *HareRequest) String() string            { return proto.CompactTextString(m) }
func (*HareRequest) ProtoMessage()               {}
func (*HareRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *HareRequest) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

type HareReply struct {
	HareSuccess   bool   `protobuf:"varint,1,opt,name=hare_success,json=hareSuccess" json:"hare_success,omitempty"`
	PoliceName    string `protobuf:"bytes,2,opt,name=police_name,json=policeName" json:"police_name,omitempty"`
	PoliceType    string `protobuf:"bytes,3,opt,name=police_type,json=policeType" json:"police_type,omitempty"`
	PoliceCity    string `protobuf:"bytes,4,opt,name=police_city,json=policeCity" json:"police_city,omitempty"`
	PoliceDept    string `protobuf:"bytes,5,opt,name=police_dept,json=policeDept" json:"police_dept,omitempty"`
	PoliceSquad   string `protobuf:"bytes,6,opt,name=police_squad,json=policeSquad" json:"police_squad,omitempty"`
	PoliceSection string `protobuf:"bytes,7,opt,name=police_section,json=policeSection" json:"police_section,omitempty"`
}

func (m *HareReply) Reset()                    { *m = HareReply{} }
func (m *HareReply) String() string            { return proto.CompactTextString(m) }
func (*HareReply) ProtoMessage()               {}
func (*HareReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *HareReply) GetHareSuccess() bool {
	if m != nil {
		return m.HareSuccess
	}
	return false
}

func (m *HareReply) GetPoliceName() string {
	if m != nil {
		return m.PoliceName
	}
	return ""
}

func (m *HareReply) GetPoliceType() string {
	if m != nil {
		return m.PoliceType
	}
	return ""
}

func (m *HareReply) GetPoliceCity() string {
	if m != nil {
		return m.PoliceCity
	}
	return ""
}

func (m *HareReply) GetPoliceDept() string {
	if m != nil {
		return m.PoliceDept
	}
	return ""
}

func (m *HareReply) GetPoliceSquad() string {
	if m != nil {
		return m.PoliceSquad
	}
	return ""
}

func (m *HareReply) GetPoliceSection() string {
	if m != nil {
		return m.PoliceSection
	}
	return ""
}

type PasswordRequest struct {
	UserId      string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Password    string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	NewPassword string `protobuf:"bytes,3,opt,name=new_password,json=newPassword" json:"new_password,omitempty"`
}

func (m *PasswordRequest) Reset()                    { *m = PasswordRequest{} }
func (m *PasswordRequest) String() string            { return proto.CompactTextString(m) }
func (*PasswordRequest) ProtoMessage()               {}
func (*PasswordRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *PasswordRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *PasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *PasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type TicketDetails struct {
	TicketId       int64   `protobuf:"varint,1,opt,name=ticket_id,json=ticketId" json:"ticket_id,omitempty"`
	UserId         string  `protobuf:"bytes,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	LicenseNum     string  `protobuf:"bytes,3,opt,name=license_num,json=licenseNum" json:"license_num,omitempty"`
	LicenseColor   string  `protobuf:"bytes,4,opt,name=license_color,json=licenseColor" json:"license_color,omitempty"`
	LicenseCorrect bool    `protobuf:"varint,5,opt,name=license_correct,json=licenseCorrect" json:"license_correct,omitempty"`
	VehicleType    string  `protobuf:"bytes,6,opt,name=vehicle_type,json=vehicleType" json:"vehicle_type,omitempty"`
	VehicleColor   string  `protobuf:"bytes,7,opt,name=vehicle_color,json=vehicleColor" json:"vehicle_color,omitempty"`
	Year           int32   `protobuf:"varint,8,opt,name=year" json:"year,omitempty"`
	Month          int32   `protobuf:"varint,9,opt,name=month" json:"month,omitempty"`
	Day            int32   `protobuf:"varint,10,opt,name=day" json:"day,omitempty"`
	Hour           int32   `protobuf:"varint,11,opt,name=hour" json:"hour,omitempty"`
	Minute         int32   `protobuf:"varint,12,opt,name=minute" json:"minute,omitempty"`
	Address        string  `protobuf:"bytes,13,opt,name=address" json:"address,omitempty"`
	Longitude      float64 `protobuf:"fixed64,14,opt,name=longitude" json:"longitude,omitempty"`
	Latitude       float64 `protobuf:"fixed64,15,opt,name=latitude" json:"latitude,omitempty"`
	MapImage       []byte  `protobuf:"bytes,16,opt,name=map_image,json=mapImage,proto3" json:"map_image,omitempty"`
	FarImage       []byte  `protobuf:"bytes,17,opt,name=far_image,json=farImage,proto3" json:"far_image,omitempty"`
	CloseImage     []byte  `protobuf:"bytes,18,opt,name=close_image,json=closeImage,proto3" json:"close_image,omitempty"`
	TicketImage    []byte  `protobuf:"bytes,19,opt,name=ticket_image,json=ticketImage,proto3" json:"ticket_image,omitempty"`
}

func (m *TicketDetails) Reset()                    { *m = TicketDetails{} }
func (m *TicketDetails) String() string            { return proto.CompactTextString(m) }
func (*TicketDetails) ProtoMessage()               {}
func (*TicketDetails) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *TicketDetails) GetTicketId() int64 {
	if m != nil {
		return m.TicketId
	}
	return 0
}

func (m *TicketDetails) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *TicketDetails) GetLicenseNum() string {
	if m != nil {
		return m.LicenseNum
	}
	return ""
}

func (m *TicketDetails) GetLicenseColor() string {
	if m != nil {
		return m.LicenseColor
	}
	return ""
}

func (m *TicketDetails) GetLicenseCorrect() bool {
	if m != nil {
		return m.LicenseCorrect
	}
	return false
}

func (m *TicketDetails) GetVehicleType() string {
	if m != nil {
		return m.VehicleType
	}
	return ""
}

func (m *TicketDetails) GetVehicleColor() string {
	if m != nil {
		return m.VehicleColor
	}
	return ""
}

func (m *TicketDetails) GetYear() int32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *TicketDetails) GetMonth() int32 {
	if m != nil {
		return m.Month
	}
	return 0
}

func (m *TicketDetails) GetDay() int32 {
	if m != nil {
		return m.Day
	}
	return 0
}

func (m *TicketDetails) GetHour() int32 {
	if m != nil {
		return m.Hour
	}
	return 0
}

func (m *TicketDetails) GetMinute() int32 {
	if m != nil {
		return m.Minute
	}
	return 0
}

func (m *TicketDetails) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *TicketDetails) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *TicketDetails) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *TicketDetails) GetMapImage() []byte {
	if m != nil {
		return m.MapImage
	}
	return nil
}

func (m *TicketDetails) GetFarImage() []byte {
	if m != nil {
		return m.FarImage
	}
	return nil
}

func (m *TicketDetails) GetCloseImage() []byte {
	if m != nil {
		return m.CloseImage
	}
	return nil
}

func (m *TicketDetails) GetTicketImage() []byte {
	if m != nil {
		return m.TicketImage
	}
	return nil
}

type RecordReply struct {
	RecordSuccess bool `protobuf:"varint,1,opt,name=record_success,json=recordSuccess" json:"record_success,omitempty"`
}

func (m *RecordReply) Reset()                    { *m = RecordReply{} }
func (m *RecordReply) String() string            { return proto.CompactTextString(m) }
func (*RecordReply) ProtoMessage()               {}
func (*RecordReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *RecordReply) GetRecordSuccess() bool {
	if m != nil {
		return m.RecordSuccess
	}
	return false
}

type TicketStats struct {
	Sid                 string `protobuf:"bytes,1,opt,name=sid" json:"sid,omitempty"`
	SavedTicketCount    int32  `protobuf:"varint,2,opt,name=saved_ticket_count,json=savedTicketCount" json:"saved_ticket_count,omitempty"`
	UploadedTicketCount int32  `protobuf:"varint,3,opt,name=uploaded_ticket_count,json=uploadedTicketCount" json:"uploaded_ticket_count,omitempty"`
}

func (m *TicketStats) Reset()                    { *m = TicketStats{} }
func (m *TicketStats) String() string            { return proto.CompactTextString(m) }
func (*TicketStats) ProtoMessage()               {}
func (*TicketStats) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *TicketStats) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *TicketStats) GetSavedTicketCount() int32 {
	if m != nil {
		return m.SavedTicketCount
	}
	return 0
}

func (m *TicketStats) GetUploadedTicketCount() int32 {
	if m != nil {
		return m.UploadedTicketCount
	}
	return 0
}

type StatsReply struct {
	StatsSuccess bool `protobuf:"varint,1,opt,name=stats_success,json=statsSuccess" json:"stats_success,omitempty"`
}

func (m *StatsReply) Reset()                    { *m = StatsReply{} }
func (m *StatsReply) String() string            { return proto.CompactTextString(m) }
func (*StatsReply) ProtoMessage()               {}
func (*StatsReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *StatsReply) GetStatsSuccess() bool {
	if m != nil {
		return m.StatsSuccess
	}
	return false
}

type PullLocRequest struct {
	Mid string `protobuf:"bytes,1,opt,name=mid" json:"mid,omitempty"`
}

func (m *PullLocRequest) Reset()                    { *m = PullLocRequest{} }
func (m *PullLocRequest) String() string            { return proto.CompactTextString(m) }
func (*PullLocRequest) ProtoMessage()               {}
func (*PullLocRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *PullLocRequest) GetMid() string {
	if m != nil {
		return m.Mid
	}
	return ""
}

type PullPerformanceRequest struct {
	Mid string `protobuf:"bytes,1,opt,name=mid" json:"mid,omitempty"`
}

func (m *PullPerformanceRequest) Reset()                    { *m = PullPerformanceRequest{} }
func (m *PullPerformanceRequest) String() string            { return proto.CompactTextString(m) }
func (*PullPerformanceRequest) ProtoMessage()               {}
func (*PullPerformanceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *PullPerformanceRequest) GetMid() string {
	if m != nil {
		return m.Mid
	}
	return ""
}

type PullAnchorRequest struct {
	Sid string `protobuf:"bytes,1,opt,name=sid" json:"sid,omitempty"`
}

func (m *PullAnchorRequest) Reset()                    { *m = PullAnchorRequest{} }
func (m *PullAnchorRequest) String() string            { return proto.CompactTextString(m) }
func (*PullAnchorRequest) ProtoMessage()               {}
func (*PullAnchorRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *PullAnchorRequest) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

type PullTicketStatsRequest struct {
	Sid string `protobuf:"bytes,1,opt,name=sid" json:"sid,omitempty"`
}

func (m *PullTicketStatsRequest) Reset()                    { *m = PullTicketStatsRequest{} }
func (m *PullTicketStatsRequest) String() string            { return proto.CompactTextString(m) }
func (*PullTicketStatsRequest) ProtoMessage()               {}
func (*PullTicketStatsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *PullTicketStatsRequest) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

type PullTicketRequest struct {
	Sid string `protobuf:"bytes,1,opt,name=sid" json:"sid,omitempty"`
}

func (m *PullTicketRequest) Reset()                    { *m = PullTicketRequest{} }
func (m *PullTicketRequest) String() string            { return proto.CompactTextString(m) }
func (*PullTicketRequest) ProtoMessage()               {}
func (*PullTicketRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *PullTicketRequest) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

type SlaveLoc struct {
	Sid       string  `protobuf:"bytes,1,opt,name=sid" json:"sid,omitempty"`
	Longitude float64 `protobuf:"fixed64,2,opt,name=longitude" json:"longitude,omitempty"`
	Latitude  float64 `protobuf:"fixed64,3,opt,name=latitude" json:"latitude,omitempty"`
}

func (m *SlaveLoc) Reset()                    { *m = SlaveLoc{} }
func (m *SlaveLoc) String() string            { return proto.CompactTextString(m) }
func (*SlaveLoc) ProtoMessage()               {}
func (*SlaveLoc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *SlaveLoc) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *SlaveLoc) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *SlaveLoc) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

type SlavePerformance struct {
	Sid              string `protobuf:"bytes,1,opt,name=sid" json:"sid,omitempty"`
	PoliceName       string `protobuf:"bytes,2,opt,name=police_name,json=policeName" json:"police_name,omitempty"`
	PoliceDept       string `protobuf:"bytes,3,opt,name=police_dept,json=policeDept" json:"police_dept,omitempty"`
	TicketCountDay   int32  `protobuf:"varint,4,opt,name=ticket_count_day,json=ticketCountDay" json:"ticket_count_day,omitempty"`
	TicketCountWeek  int32  `protobuf:"varint,5,opt,name=ticket_count_week,json=ticketCountWeek" json:"ticket_count_week,omitempty"`
	TicketCountMonth int32  `protobuf:"varint,6,opt,name=ticket_count_month,json=ticketCountMonth" json:"ticket_count_month,omitempty"`
}

func (m *SlavePerformance) Reset()                    { *m = SlavePerformance{} }
func (m *SlavePerformance) String() string            { return proto.CompactTextString(m) }
func (*SlavePerformance) ProtoMessage()               {}
func (*SlavePerformance) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *SlavePerformance) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *SlavePerformance) GetPoliceName() string {
	if m != nil {
		return m.PoliceName
	}
	return ""
}

func (m *SlavePerformance) GetPoliceDept() string {
	if m != nil {
		return m.PoliceDept
	}
	return ""
}

func (m *SlavePerformance) GetTicketCountDay() int32 {
	if m != nil {
		return m.TicketCountDay
	}
	return 0
}

func (m *SlavePerformance) GetTicketCountWeek() int32 {
	if m != nil {
		return m.TicketCountWeek
	}
	return 0
}

func (m *SlavePerformance) GetTicketCountMonth() int32 {
	if m != nil {
		return m.TicketCountMonth
	}
	return 0
}

type MasterOrder struct {
	Mid         string `protobuf:"bytes,1,opt,name=mid" json:"mid,omitempty"`
	MasterOrder string `protobuf:"bytes,2,opt,name=master_order,json=masterOrder" json:"master_order,omitempty"`
}

func (m *MasterOrder) Reset()                    { *m = MasterOrder{} }
func (m *MasterOrder) String() string            { return proto.CompactTextString(m) }
func (*MasterOrder) ProtoMessage()               {}
func (*MasterOrder) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *MasterOrder) GetMid() string {
	if m != nil {
		return m.Mid
	}
	return ""
}

func (m *MasterOrder) GetMasterOrder() string {
	if m != nil {
		return m.MasterOrder
	}
	return ""
}

type SlaveAnchors struct {
	Sid         string  `protobuf:"bytes,1,opt,name=sid" json:"sid,omitempty"`
	AnchorCount int32   `protobuf:"varint,2,opt,name=anchor_count,json=anchorCount" json:"anchor_count,omitempty"`
	Anchor0Lng  float64 `protobuf:"fixed64,3,opt,name=anchor0_lng,json=anchor0Lng" json:"anchor0_lng,omitempty"`
	Anchor0Lat  float64 `protobuf:"fixed64,4,opt,name=anchor0_lat,json=anchor0Lat" json:"anchor0_lat,omitempty"`
	Anchor1Lng  float64 `protobuf:"fixed64,5,opt,name=anchor1_lng,json=anchor1Lng" json:"anchor1_lng,omitempty"`
	Anchor1Lat  float64 `protobuf:"fixed64,6,opt,name=anchor1_lat,json=anchor1Lat" json:"anchor1_lat,omitempty"`
	Anchor2Lng  float64 `protobuf:"fixed64,7,opt,name=anchor2_lng,json=anchor2Lng" json:"anchor2_lng,omitempty"`
	Anchor2Lat  float64 `protobuf:"fixed64,8,opt,name=anchor2_lat,json=anchor2Lat" json:"anchor2_lat,omitempty"`
	Anchor3Lng  float64 `protobuf:"fixed64,9,opt,name=anchor3_lng,json=anchor3Lng" json:"anchor3_lng,omitempty"`
	Anchor3Lat  float64 `protobuf:"fixed64,10,opt,name=anchor3_lat,json=anchor3Lat" json:"anchor3_lat,omitempty"`
	Anchor4Lng  float64 `protobuf:"fixed64,11,opt,name=anchor4_lng,json=anchor4Lng" json:"anchor4_lng,omitempty"`
	Anchor4Lat  float64 `protobuf:"fixed64,12,opt,name=anchor4_lat,json=anchor4Lat" json:"anchor4_lat,omitempty"`
	Anchor5Lng  float64 `protobuf:"fixed64,13,opt,name=anchor5_lng,json=anchor5Lng" json:"anchor5_lng,omitempty"`
	Anchor5Lat  float64 `protobuf:"fixed64,14,opt,name=anchor5_lat,json=anchor5Lat" json:"anchor5_lat,omitempty"`
}

func (m *SlaveAnchors) Reset()                    { *m = SlaveAnchors{} }
func (m *SlaveAnchors) String() string            { return proto.CompactTextString(m) }
func (*SlaveAnchors) ProtoMessage()               {}
func (*SlaveAnchors) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *SlaveAnchors) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *SlaveAnchors) GetAnchorCount() int32 {
	if m != nil {
		return m.AnchorCount
	}
	return 0
}

func (m *SlaveAnchors) GetAnchor0Lng() float64 {
	if m != nil {
		return m.Anchor0Lng
	}
	return 0
}

func (m *SlaveAnchors) GetAnchor0Lat() float64 {
	if m != nil {
		return m.Anchor0Lat
	}
	return 0
}

func (m *SlaveAnchors) GetAnchor1Lng() float64 {
	if m != nil {
		return m.Anchor1Lng
	}
	return 0
}

func (m *SlaveAnchors) GetAnchor1Lat() float64 {
	if m != nil {
		return m.Anchor1Lat
	}
	return 0
}

func (m *SlaveAnchors) GetAnchor2Lng() float64 {
	if m != nil {
		return m.Anchor2Lng
	}
	return 0
}

func (m *SlaveAnchors) GetAnchor2Lat() float64 {
	if m != nil {
		return m.Anchor2Lat
	}
	return 0
}

func (m *SlaveAnchors) GetAnchor3Lng() float64 {
	if m != nil {
		return m.Anchor3Lng
	}
	return 0
}

func (m *SlaveAnchors) GetAnchor3Lat() float64 {
	if m != nil {
		return m.Anchor3Lat
	}
	return 0
}

func (m *SlaveAnchors) GetAnchor4Lng() float64 {
	if m != nil {
		return m.Anchor4Lng
	}
	return 0
}

func (m *SlaveAnchors) GetAnchor4Lat() float64 {
	if m != nil {
		return m.Anchor4Lat
	}
	return 0
}

func (m *SlaveAnchors) GetAnchor5Lng() float64 {
	if m != nil {
		return m.Anchor5Lng
	}
	return 0
}

func (m *SlaveAnchors) GetAnchor5Lat() float64 {
	if m != nil {
		return m.Anchor5Lat
	}
	return 0
}

type TicketRange struct {
	TicketIdStart int64 `protobuf:"varint,1,opt,name=ticket_id_start,json=ticketIdStart" json:"ticket_id_start,omitempty"`
	TicketIdEnd   int64 `protobuf:"varint,2,opt,name=ticket_id_end,json=ticketIdEnd" json:"ticket_id_end,omitempty"`
}

func (m *TicketRange) Reset()                    { *m = TicketRange{} }
func (m *TicketRange) String() string            { return proto.CompactTextString(m) }
func (*TicketRange) ProtoMessage()               {}
func (*TicketRange) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *TicketRange) GetTicketIdStart() int64 {
	if m != nil {
		return m.TicketIdStart
	}
	return 0
}

func (m *TicketRange) GetTicketIdEnd() int64 {
	if m != nil {
		return m.TicketIdEnd
	}
	return 0
}

type TicketRangeReply struct {
	RangeSuccess bool `protobuf:"varint,1,opt,name=range_success,json=rangeSuccess" json:"range_success,omitempty"`
}

func (m *TicketRangeReply) Reset()                    { *m = TicketRangeReply{} }
func (m *TicketRangeReply) String() string            { return proto.CompactTextString(m) }
func (*TicketRangeReply) ProtoMessage()               {}
func (*TicketRangeReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *TicketRangeReply) GetRangeSuccess() bool {
	if m != nil {
		return m.RangeSuccess
	}
	return false
}

type TicketRangeSid struct {
	Sid string `protobuf:"bytes,1,opt,name=sid" json:"sid,omitempty"`
}

func (m *TicketRangeSid) Reset()                    { *m = TicketRangeSid{} }
func (m *TicketRangeSid) String() string            { return proto.CompactTextString(m) }
func (*TicketRangeSid) ProtoMessage()               {}
func (*TicketRangeSid) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *TicketRangeSid) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func init() {
	proto.RegisterType((*AccountRequest)(nil), "ticket.AccountRequest")
	proto.RegisterType((*AccountReply)(nil), "ticket.AccountReply")
	proto.RegisterType((*LoginRequest)(nil), "ticket.LoginRequest")
	proto.RegisterType((*LoginReply)(nil), "ticket.LoginReply")
	proto.RegisterType((*HareRequest)(nil), "ticket.HareRequest")
	proto.RegisterType((*HareReply)(nil), "ticket.HareReply")
	proto.RegisterType((*PasswordRequest)(nil), "ticket.PasswordRequest")
	proto.RegisterType((*TicketDetails)(nil), "ticket.TicketDetails")
	proto.RegisterType((*RecordReply)(nil), "ticket.RecordReply")
	proto.RegisterType((*TicketStats)(nil), "ticket.TicketStats")
	proto.RegisterType((*StatsReply)(nil), "ticket.StatsReply")
	proto.RegisterType((*PullLocRequest)(nil), "ticket.PullLocRequest")
	proto.RegisterType((*PullPerformanceRequest)(nil), "ticket.PullPerformanceRequest")
	proto.RegisterType((*PullAnchorRequest)(nil), "ticket.PullAnchorRequest")
	proto.RegisterType((*PullTicketStatsRequest)(nil), "ticket.PullTicketStatsRequest")
	proto.RegisterType((*PullTicketRequest)(nil), "ticket.PullTicketRequest")
	proto.RegisterType((*SlaveLoc)(nil), "ticket.SlaveLoc")
	proto.RegisterType((*SlavePerformance)(nil), "ticket.SlavePerformance")
	proto.RegisterType((*MasterOrder)(nil), "ticket.MasterOrder")
	proto.RegisterType((*SlaveAnchors)(nil), "ticket.SlaveAnchors")
	proto.RegisterType((*TicketRange)(nil), "ticket.TicketRange")
	proto.RegisterType((*TicketRangeReply)(nil), "ticket.TicketRangeReply")
	proto.RegisterType((*TicketRangeSid)(nil), "ticket.TicketRangeSid")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Ticket service

type TicketClient interface {
	RhinoCreateAccount(ctx context.Context, in *AccountRequest, opts ...grpc.CallOption) (*AccountReply, error)
	RhinoLogin(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error)
	RhinoChangePassword(ctx context.Context, in *PasswordRequest, opts ...grpc.CallOption) (*LoginReply, error)
	PullHare(ctx context.Context, in *HareRequest, opts ...grpc.CallOption) (*HareReply, error)
	HareCreateAccount(ctx context.Context, in *AccountRequest, opts ...grpc.CallOption) (*AccountReply, error)
	HareLogin(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error)
	HareChangePassword(ctx context.Context, in *PasswordRequest, opts ...grpc.CallOption) (*LoginReply, error)
	RecordTicket(ctx context.Context, in *TicketDetails, opts ...grpc.CallOption) (*RecordReply, error)
	SubmitTicketStats(ctx context.Context, in *TicketStats, opts ...grpc.CallOption) (*StatsReply, error)
	SlaveLocSubmit(ctx context.Context, in *SlaveLoc, opts ...grpc.CallOption) (*MasterOrder, error)
	SlaveAnchorSubmit(ctx context.Context, in *SlaveLoc, opts ...grpc.CallOption) (*MasterOrder, error)
	MasterReceive(ctx context.Context, opts ...grpc.CallOption) (Ticket_MasterReceiveClient, error)
	PullLocation(ctx context.Context, in *PullLocRequest, opts ...grpc.CallOption) (Ticket_PullLocationClient, error)
	PullPerformance(ctx context.Context, in *PullPerformanceRequest, opts ...grpc.CallOption) (Ticket_PullPerformanceClient, error)
	PullAnchors(ctx context.Context, in *PullAnchorRequest, opts ...grpc.CallOption) (*SlaveAnchors, error)
	PullTicketStats(ctx context.Context, in *PullTicketStatsRequest, opts ...grpc.CallOption) (*TicketStats, error)
	PullTicket(ctx context.Context, in *PullTicketRequest, opts ...grpc.CallOption) (Ticket_PullTicketClient, error)
	SetTicketRange(ctx context.Context, in *TicketRange, opts ...grpc.CallOption) (*TicketRangeReply, error)
	PullTicketRange(ctx context.Context, in *TicketRangeSid, opts ...grpc.CallOption) (*TicketRange, error)
}

type ticketClient struct {
	cc *grpc.ClientConn
}

func NewTicketClient(cc *grpc.ClientConn) TicketClient {
	return &ticketClient{cc}
}

func (c *ticketClient) RhinoCreateAccount(ctx context.Context, in *AccountRequest, opts ...grpc.CallOption) (*AccountReply, error) {
	out := new(AccountReply)
	err := grpc.Invoke(ctx, "/ticket.Ticket/RhinoCreateAccount", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketClient) RhinoLogin(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error) {
	out := new(LoginReply)
	err := grpc.Invoke(ctx, "/ticket.Ticket/RhinoLogin", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketClient) RhinoChangePassword(ctx context.Context, in *PasswordRequest, opts ...grpc.CallOption) (*LoginReply, error) {
	out := new(LoginReply)
	err := grpc.Invoke(ctx, "/ticket.Ticket/RhinoChangePassword", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketClient) PullHare(ctx context.Context, in *HareRequest, opts ...grpc.CallOption) (*HareReply, error) {
	out := new(HareReply)
	err := grpc.Invoke(ctx, "/ticket.Ticket/PullHare", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketClient) HareCreateAccount(ctx context.Context, in *AccountRequest, opts ...grpc.CallOption) (*AccountReply, error) {
	out := new(AccountReply)
	err := grpc.Invoke(ctx, "/ticket.Ticket/HareCreateAccount", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketClient) HareLogin(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error) {
	out := new(LoginReply)
	err := grpc.Invoke(ctx, "/ticket.Ticket/HareLogin", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketClient) HareChangePassword(ctx context.Context, in *PasswordRequest, opts ...grpc.CallOption) (*LoginReply, error) {
	out := new(LoginReply)
	err := grpc.Invoke(ctx, "/ticket.Ticket/HareChangePassword", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketClient) RecordTicket(ctx context.Context, in *TicketDetails, opts ...grpc.CallOption) (*RecordReply, error) {
	out := new(RecordReply)
	err := grpc.Invoke(ctx, "/ticket.Ticket/RecordTicket", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketClient) SubmitTicketStats(ctx context.Context, in *TicketStats, opts ...grpc.CallOption) (*StatsReply, error) {
	out := new(StatsReply)
	err := grpc.Invoke(ctx, "/ticket.Ticket/SubmitTicketStats", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketClient) SlaveLocSubmit(ctx context.Context, in *SlaveLoc, opts ...grpc.CallOption) (*MasterOrder, error) {
	out := new(MasterOrder)
	err := grpc.Invoke(ctx, "/ticket.Ticket/SlaveLocSubmit", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketClient) SlaveAnchorSubmit(ctx context.Context, in *SlaveLoc, opts ...grpc.CallOption) (*MasterOrder, error) {
	out := new(MasterOrder)
	err := grpc.Invoke(ctx, "/ticket.Ticket/SlaveAnchorSubmit", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketClient) MasterReceive(ctx context.Context, opts ...grpc.CallOption) (Ticket_MasterReceiveClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Ticket_serviceDesc.Streams[0], c.cc, "/ticket.Ticket/MasterReceive", opts...)
	if err != nil {
		return nil, err
	}
	x := &ticketMasterReceiveClient{stream}
	return x, nil
}

type Ticket_MasterReceiveClient interface {
	Send(*MasterOrder) error
	Recv() (*SlaveLoc, error)
	grpc.ClientStream
}

type ticketMasterReceiveClient struct {
	grpc.ClientStream
}

func (x *ticketMasterReceiveClient) Send(m *MasterOrder) error {
	return x.ClientStream.SendMsg(m)
}

func (x *ticketMasterReceiveClient) Recv() (*SlaveLoc, error) {
	m := new(SlaveLoc)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *ticketClient) PullLocation(ctx context.Context, in *PullLocRequest, opts ...grpc.CallOption) (Ticket_PullLocationClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Ticket_serviceDesc.Streams[1], c.cc, "/ticket.Ticket/PullLocation", opts...)
	if err != nil {
		return nil, err
	}
	x := &ticketPullLocationClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Ticket_PullLocationClient interface {
	Recv() (*SlaveLoc, error)
	grpc.ClientStream
}

type ticketPullLocationClient struct {
	grpc.ClientStream
}

func (x *ticketPullLocationClient) Recv() (*SlaveLoc, error) {
	m := new(SlaveLoc)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *ticketClient) PullPerformance(ctx context.Context, in *PullPerformanceRequest, opts ...grpc.CallOption) (Ticket_PullPerformanceClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Ticket_serviceDesc.Streams[2], c.cc, "/ticket.Ticket/PullPerformance", opts...)
	if err != nil {
		return nil, err
	}
	x := &ticketPullPerformanceClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Ticket_PullPerformanceClient interface {
	Recv() (*SlavePerformance, error)
	grpc.ClientStream
}

type ticketPullPerformanceClient struct {
	grpc.ClientStream
}

func (x *ticketPullPerformanceClient) Recv() (*SlavePerformance, error) {
	m := new(SlavePerformance)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *ticketClient) PullAnchors(ctx context.Context, in *PullAnchorRequest, opts ...grpc.CallOption) (*SlaveAnchors, error) {
	out := new(SlaveAnchors)
	err := grpc.Invoke(ctx, "/ticket.Ticket/PullAnchors", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketClient) PullTicketStats(ctx context.Context, in *PullTicketStatsRequest, opts ...grpc.CallOption) (*TicketStats, error) {
	out := new(TicketStats)
	err := grpc.Invoke(ctx, "/ticket.Ticket/PullTicketStats", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketClient) PullTicket(ctx context.Context, in *PullTicketRequest, opts ...grpc.CallOption) (Ticket_PullTicketClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Ticket_serviceDesc.Streams[3], c.cc, "/ticket.Ticket/PullTicket", opts...)
	if err != nil {
		return nil, err
	}
	x := &ticketPullTicketClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Ticket_PullTicketClient interface {
	Recv() (*TicketDetails, error)
	grpc.ClientStream
}

type ticketPullTicketClient struct {
	grpc.ClientStream
}

func (x *ticketPullTicketClient) Recv() (*TicketDetails, error) {
	m := new(TicketDetails)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *ticketClient) SetTicketRange(ctx context.Context, in *TicketRange, opts ...grpc.CallOption) (*TicketRangeReply, error) {
	out := new(TicketRangeReply)
	err := grpc.Invoke(ctx, "/ticket.Ticket/SetTicketRange", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketClient) PullTicketRange(ctx context.Context, in *TicketRangeSid, opts ...grpc.CallOption) (*TicketRange, error) {
	out := new(TicketRange)
	err := grpc.Invoke(ctx, "/ticket.Ticket/PullTicketRange", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Ticket service

type TicketServer interface {
	RhinoCreateAccount(context.Context, *AccountRequest) (*AccountReply, error)
	RhinoLogin(context.Context, *LoginRequest) (*LoginReply, error)
	RhinoChangePassword(context.Context, *PasswordRequest) (*LoginReply, error)
	PullHare(context.Context, *HareRequest) (*HareReply, error)
	HareCreateAccount(context.Context, *AccountRequest) (*AccountReply, error)
	HareLogin(context.Context, *LoginRequest) (*LoginReply, error)
	HareChangePassword(context.Context, *PasswordRequest) (*LoginReply, error)
	RecordTicket(context.Context, *TicketDetails) (*RecordReply, error)
	SubmitTicketStats(context.Context, *TicketStats) (*StatsReply, error)
	SlaveLocSubmit(context.Context, *SlaveLoc) (*MasterOrder, error)
	SlaveAnchorSubmit(context.Context, *SlaveLoc) (*MasterOrder, error)
	MasterReceive(Ticket_MasterReceiveServer) error
	PullLocation(*PullLocRequest, Ticket_PullLocationServer) error
	PullPerformance(*PullPerformanceRequest, Ticket_PullPerformanceServer) error
	PullAnchors(context.Context, *PullAnchorRequest) (*SlaveAnchors, error)
	PullTicketStats(context.Context, *PullTicketStatsRequest) (*TicketStats, error)
	PullTicket(*PullTicketRequest, Ticket_PullTicketServer) error
	SetTicketRange(context.Context, *TicketRange) (*TicketRangeReply, error)
	PullTicketRange(context.Context, *TicketRangeSid) (*TicketRange, error)
}

func RegisterTicketServer(s *grpc.Server, srv TicketServer) {
	s.RegisterService(&_Ticket_serviceDesc, srv)
}

func _Ticket_RhinoCreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServer).RhinoCreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ticket.Ticket/RhinoCreateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServer).RhinoCreateAccount(ctx, req.(*AccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ticket_RhinoLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServer).RhinoLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ticket.Ticket/RhinoLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServer).RhinoLogin(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ticket_RhinoChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServer).RhinoChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ticket.Ticket/RhinoChangePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServer).RhinoChangePassword(ctx, req.(*PasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ticket_PullHare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServer).PullHare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ticket.Ticket/PullHare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServer).PullHare(ctx, req.(*HareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ticket_HareCreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServer).HareCreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ticket.Ticket/HareCreateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServer).HareCreateAccount(ctx, req.(*AccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ticket_HareLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServer).HareLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ticket.Ticket/HareLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServer).HareLogin(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ticket_HareChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServer).HareChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ticket.Ticket/HareChangePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServer).HareChangePassword(ctx, req.(*PasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ticket_RecordTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TicketDetails)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServer).RecordTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ticket.Ticket/RecordTicket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServer).RecordTicket(ctx, req.(*TicketDetails))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ticket_SubmitTicketStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TicketStats)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServer).SubmitTicketStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ticket.Ticket/SubmitTicketStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServer).SubmitTicketStats(ctx, req.(*TicketStats))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ticket_SlaveLocSubmit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SlaveLoc)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServer).SlaveLocSubmit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ticket.Ticket/SlaveLocSubmit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServer).SlaveLocSubmit(ctx, req.(*SlaveLoc))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ticket_SlaveAnchorSubmit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SlaveLoc)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServer).SlaveAnchorSubmit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ticket.Ticket/SlaveAnchorSubmit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServer).SlaveAnchorSubmit(ctx, req.(*SlaveLoc))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ticket_MasterReceive_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TicketServer).MasterReceive(&ticketMasterReceiveServer{stream})
}

type Ticket_MasterReceiveServer interface {
	Send(*SlaveLoc) error
	Recv() (*MasterOrder, error)
	grpc.ServerStream
}

type ticketMasterReceiveServer struct {
	grpc.ServerStream
}

func (x *ticketMasterReceiveServer) Send(m *SlaveLoc) error {
	return x.ServerStream.SendMsg(m)
}

func (x *ticketMasterReceiveServer) Recv() (*MasterOrder, error) {
	m := new(MasterOrder)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Ticket_PullLocation_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PullLocRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TicketServer).PullLocation(m, &ticketPullLocationServer{stream})
}

type Ticket_PullLocationServer interface {
	Send(*SlaveLoc) error
	grpc.ServerStream
}

type ticketPullLocationServer struct {
	grpc.ServerStream
}

func (x *ticketPullLocationServer) Send(m *SlaveLoc) error {
	return x.ServerStream.SendMsg(m)
}

func _Ticket_PullPerformance_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PullPerformanceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TicketServer).PullPerformance(m, &ticketPullPerformanceServer{stream})
}

type Ticket_PullPerformanceServer interface {
	Send(*SlavePerformance) error
	grpc.ServerStream
}

type ticketPullPerformanceServer struct {
	grpc.ServerStream
}

func (x *ticketPullPerformanceServer) Send(m *SlavePerformance) error {
	return x.ServerStream.SendMsg(m)
}

func _Ticket_PullAnchors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullAnchorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServer).PullAnchors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ticket.Ticket/PullAnchors",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServer).PullAnchors(ctx, req.(*PullAnchorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ticket_PullTicketStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullTicketStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServer).PullTicketStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ticket.Ticket/PullTicketStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServer).PullTicketStats(ctx, req.(*PullTicketStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ticket_PullTicket_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PullTicketRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TicketServer).PullTicket(m, &ticketPullTicketServer{stream})
}

type Ticket_PullTicketServer interface {
	Send(*TicketDetails) error
	grpc.ServerStream
}

type ticketPullTicketServer struct {
	grpc.ServerStream
}

func (x *ticketPullTicketServer) Send(m *TicketDetails) error {
	return x.ServerStream.SendMsg(m)
}

func _Ticket_SetTicketRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TicketRange)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServer).SetTicketRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ticket.Ticket/SetTicketRange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServer).SetTicketRange(ctx, req.(*TicketRange))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ticket_PullTicketRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TicketRangeSid)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServer).PullTicketRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ticket.Ticket/PullTicketRange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServer).PullTicketRange(ctx, req.(*TicketRangeSid))
	}
	return interceptor(ctx, in, info, handler)
}

var _Ticket_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ticket.Ticket",
	HandlerType: (*TicketServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RhinoCreateAccount",
			Handler:    _Ticket_RhinoCreateAccount_Handler,
		},
		{
			MethodName: "RhinoLogin",
			Handler:    _Ticket_RhinoLogin_Handler,
		},
		{
			MethodName: "RhinoChangePassword",
			Handler:    _Ticket_RhinoChangePassword_Handler,
		},
		{
			MethodName: "PullHare",
			Handler:    _Ticket_PullHare_Handler,
		},
		{
			MethodName: "HareCreateAccount",
			Handler:    _Ticket_HareCreateAccount_Handler,
		},
		{
			MethodName: "HareLogin",
			Handler:    _Ticket_HareLogin_Handler,
		},
		{
			MethodName: "HareChangePassword",
			Handler:    _Ticket_HareChangePassword_Handler,
		},
		{
			MethodName: "RecordTicket",
			Handler:    _Ticket_RecordTicket_Handler,
		},
		{
			MethodName: "SubmitTicketStats",
			Handler:    _Ticket_SubmitTicketStats_Handler,
		},
		{
			MethodName: "SlaveLocSubmit",
			Handler:    _Ticket_SlaveLocSubmit_Handler,
		},
		{
			MethodName: "SlaveAnchorSubmit",
			Handler:    _Ticket_SlaveAnchorSubmit_Handler,
		},
		{
			MethodName: "PullAnchors",
			Handler:    _Ticket_PullAnchors_Handler,
		},
		{
			MethodName: "PullTicketStats",
			Handler:    _Ticket_PullTicketStats_Handler,
		},
		{
			MethodName: "SetTicketRange",
			Handler:    _Ticket_SetTicketRange_Handler,
		},
		{
			MethodName: "PullTicketRange",
			Handler:    _Ticket_PullTicketRange_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "MasterReceive",
			Handler:       _Ticket_MasterReceive_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "PullLocation",
			Handler:       _Ticket_PullLocation_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PullPerformance",
			Handler:       _Ticket_PullPerformance_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PullTicket",
			Handler:       _Ticket_PullTicket_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ticket.proto",
}

func init() { proto.RegisterFile("ticket.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1431 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x58, 0xcf, 0x6e, 0x1b, 0xb7,
	0x13, 0x96, 0x2c, 0x4b, 0x96, 0x67, 0x57, 0xb2, 0x44, 0x27, 0xce, 0xfe, 0xf4, 0x2b, 0x6a, 0x7b,
	0x83, 0xb4, 0x46, 0x50, 0x04, 0xf1, 0x3f, 0xa4, 0x05, 0x8a, 0x22, 0xb1, 0x5c, 0x20, 0x01, 0x9c,
	0xc4, 0x58, 0x05, 0x2d, 0x7a, 0x12, 0x98, 0x5d, 0xc6, 0x5a, 0x64, 0xff, 0x28, 0xbb, 0x94, 0x0d,
	0xf5, 0xd6, 0xb7, 0xe9, 0x13, 0xf4, 0xd4, 0x77, 0xe8, 0x2b, 0xf4, 0xdc, 0x67, 0xe8, 0xa1, 0xe0,
	0x90, 0xbb, 0x22, 0x25, 0xb9, 0x4e, 0xe0, 0x5b, 0x6f, 0xcb, 0x8f, 0xdf, 0x7c, 0x24, 0x67, 0x86,
	0xc3, 0x91, 0xc0, 0xe6, 0xa1, 0xff, 0x9e, 0xf1, 0x47, 0xe3, 0x2c, 0xe5, 0x29, 0x69, 0xc8, 0x91,
	0xfb, 0xfb, 0x0a, 0xb4, 0x9f, 0xf9, 0x7e, 0x3a, 0x49, 0xb8, 0xc7, 0x3e, 0x4c, 0x58, 0xce, 0xc9,
	0x3d, 0x58, 0x9b, 0xe4, 0x2c, 0x1b, 0x86, 0x81, 0x53, 0xdd, 0xa9, 0xee, 0xad, 0x7b, 0x0d, 0x31,
	0x7c, 0x11, 0x90, 0x1e, 0x34, 0xc7, 0x34, 0xcf, 0xaf, 0xd2, 0x2c, 0x70, 0x56, 0x70, 0xa6, 0x1c,
	0x93, 0x6d, 0xb0, 0xc6, 0x69, 0x14, 0xfa, 0x6c, 0x98, 0xd0, 0x98, 0x39, 0x35, 0x9c, 0x06, 0x09,
	0xbd, 0xa2, 0x31, 0xd3, 0x08, 0x7c, 0x3a, 0x66, 0xce, 0xaa, 0x4e, 0x78, 0x33, 0x1d, 0xeb, 0x04,
	0x3f, 0xe4, 0x53, 0xa7, 0xae, 0x13, 0xfa, 0x21, 0x9f, 0x6a, 0x84, 0x80, 0x8d, 0xb9, 0xd3, 0xd0,
	0x09, 0xa7, 0x6c, 0xcc, 0xc9, 0x2e, 0xd8, 0x8a, 0x90, 0x7f, 0x98, 0xd0, 0xc0, 0x59, 0x43, 0x86,
	0x32, 0x1a, 0x08, 0x88, 0x3c, 0x80, 0x76, 0x41, 0x61, 0x3e, 0x0f, 0xd3, 0xc4, 0x69, 0x22, 0xa9,
	0xa5, 0x48, 0x12, 0x24, 0x5f, 0xc2, 0x86, 0xa2, 0x8d, 0xd3, 0x8c, 0x67, 0x34, 0xe4, 0xce, 0xfa,
	0x4e, 0x75, 0xcf, 0xf6, 0x94, 0xf5, 0xb9, 0x42, 0xdd, 0x63, 0xb0, 0x4b, 0xef, 0x8d, 0xa3, 0xa9,
	0xd0, 0xf7, 0x33, 0x46, 0x39, 0x1b, 0xe6, 0x13, 0xdf, 0x67, 0x79, 0x8e, 0x2e, 0x6c, 0x7a, 0x2d,
	0x89, 0x0e, 0x24, 0xe8, 0xf6, 0xc1, 0x3e, 0x4b, 0x2f, 0xc2, 0xe4, 0x36, 0x2e, 0x77, 0x7f, 0x5d,
	0x01, 0x50, 0x2a, 0x62, 0xe9, 0xfb, 0xd0, 0x8a, 0xc4, 0x68, 0x6e, 0x65, 0x1b, 0x41, 0xb5, 0xf0,
	0x7c, 0x98, 0x56, 0x6e, 0x0a, 0x53, 0xed, 0xa6, 0x30, 0xad, 0xde, 0x14, 0xa6, 0xfa, 0x8d, 0x61,
	0x6a, 0x7c, 0x4c, 0x98, 0xd6, 0x3e, 0x32, 0x4c, 0xcd, 0xa5, 0x61, 0xda, 0x06, 0xeb, 0x39, 0xcd,
	0x58, 0xe1, 0xee, 0x0e, 0xd4, 0xf2, 0xd2, 0xd5, 0xe2, 0xd3, 0xfd, 0xbb, 0x0a, 0xeb, 0x92, 0x21,
	0x5c, 0xb9, 0x0b, 0xf6, 0x88, 0x66, 0xf3, 0x31, 0xb4, 0x04, 0xf6, 0x9f, 0x74, 0xa4, 0x1b, 0xc2,
	0xc6, 0xb9, 0x4a, 0xab, 0x5b, 0x55, 0x81, 0x5d, 0xb0, 0x13, 0x76, 0x35, 0x2c, 0xe7, 0xe5, 0xa9,
	0xad, 0x84, 0x5d, 0x15, 0xf2, 0xee, 0x6f, 0xab, 0xd0, 0x7a, 0x83, 0xb5, 0xe7, 0x94, 0x71, 0x1a,
	0x46, 0x39, 0xf9, 0x3f, 0xac, 0xcb, 0x62, 0x54, 0xac, 0x55, 0xf3, 0x9a, 0x12, 0x78, 0x11, 0xe8,
	0xdb, 0x58, 0x31, 0xb6, 0xb1, 0x0d, 0x96, 0x38, 0x41, 0x92, 0xb3, 0x61, 0x32, 0x89, 0x0b, 0xff,
	0x2a, 0xe8, 0xd5, 0x24, 0xc6, 0xfb, 0xa0, 0x08, 0x7e, 0x1a, 0xa5, 0x99, 0xf2, 0xb0, 0xad, 0xc0,
	0xbe, 0xc0, 0x44, 0x06, 0xcd, 0x48, 0x59, 0xc6, 0x7c, 0xe9, 0xe7, 0xa6, 0xd7, 0x2e, 0x69, 0x88,
	0x8a, 0x93, 0x5d, 0xb2, 0x51, 0xe8, 0x47, 0x2a, 0x9e, 0xca, 0xd7, 0x0a, 0xc3, 0x80, 0xde, 0x87,
	0x56, 0x41, 0x91, 0x0b, 0x4a, 0x57, 0x17, 0x76, 0x72, 0x41, 0x02, 0xab, 0x53, 0x46, 0x33, 0xcc,
	0xd3, 0xba, 0x87, 0xdf, 0xe4, 0x0e, 0xd4, 0xe3, 0x34, 0xe1, 0x23, 0xac, 0x31, 0x75, 0x4f, 0x0e,
	0x44, 0x92, 0x06, 0x74, 0xea, 0x00, 0x62, 0xe2, 0x53, 0xd8, 0x8e, 0xd2, 0x49, 0xe6, 0x58, 0xd2,
	0x56, 0x7c, 0x93, 0x2d, 0x68, 0xc4, 0x61, 0x32, 0xe1, 0xcc, 0xb1, 0x11, 0x55, 0x23, 0xe2, 0xc0,
	0x1a, 0x0d, 0x82, 0x4c, 0x64, 0x6f, 0x0b, 0xb7, 0x51, 0x0c, 0xc9, 0x67, 0xb0, 0x1e, 0xa5, 0xc9,
	0x45, 0xc8, 0x27, 0x01, 0x73, 0xda, 0x3b, 0xd5, 0xbd, 0xaa, 0x37, 0x03, 0x44, 0x74, 0x23, 0xca,
	0xe5, 0xe4, 0x06, 0x4e, 0x96, 0x63, 0x11, 0xa8, 0x98, 0x8e, 0x87, 0x61, 0x4c, 0x2f, 0x98, 0xd3,
	0xc1, 0x8b, 0xd6, 0x8c, 0xe9, 0xf8, 0x85, 0x18, 0x8b, 0xc9, 0x77, 0x34, 0x53, 0x93, 0x5d, 0x39,
	0xf9, 0x8e, 0x66, 0x72, 0x72, 0x1b, 0x2c, 0x3f, 0x4a, 0x73, 0xa6, 0xa6, 0x09, 0x4e, 0x03, 0x42,
	0x92, 0xb0, 0x5b, 0x3c, 0x4f, 0x8a, 0xb1, 0x89, 0x0c, 0x4b, 0xa5, 0x81, 0x80, 0xdc, 0x23, 0xb0,
	0x3c, 0xe6, 0x63, 0x86, 0xaa, 0x4a, 0x9b, 0xe1, 0x70, 0xbe, 0xd2, 0x4a, 0xb4, 0xa8, 0xb4, 0xbf,
	0x54, 0xc1, 0x92, 0xe9, 0x36, 0xe0, 0x94, 0xe7, 0x8b, 0x57, 0x9f, 0x7c, 0x05, 0x24, 0xa7, 0x97,
	0x2c, 0x18, 0xaa, 0x0d, 0x60, 0x35, 0xc7, 0x64, 0xab, 0x7b, 0x1d, 0x9c, 0x91, 0xf6, 0x7d, 0x81,
	0x93, 0x03, 0xb8, 0x3b, 0x19, 0x47, 0x29, 0x0d, 0xe6, 0x0d, 0x6a, 0x68, 0xb0, 0x59, 0x4c, 0x6a,
	0x36, 0xee, 0x3e, 0x00, 0x2e, 0x5e, 0xd6, 0xe9, 0x5c, 0x8c, 0xe6, 0xeb, 0x34, 0x82, 0xc5, 0xb6,
	0x5d, 0x68, 0x9f, 0x4f, 0xa2, 0xe8, 0x2c, 0xf5, 0xb5, 0x9a, 0x15, 0xcf, 0x36, 0x1e, 0x87, 0x81,
	0xfb, 0x10, 0xb6, 0x04, 0xe7, 0x9c, 0x65, 0xef, 0xd2, 0x2c, 0xa6, 0x89, 0xcf, 0xae, 0xe7, 0x3e,
	0x80, 0xae, 0xe0, 0x3e, 0x4b, 0xfc, 0x51, 0x9a, 0x5d, 0x5f, 0x06, 0x95, 0xa4, 0xe6, 0xb0, 0xeb,
	0xb9, 0x4a, 0x52, 0x72, 0xaf, 0xa7, 0xfd, 0x00, 0xcd, 0x41, 0x44, 0x2f, 0xd9, 0x59, 0xea, 0x2f,
	0x71, 0xbe, 0x91, 0x8c, 0x2b, 0xff, 0x96, 0x8c, 0x35, 0x33, 0x19, 0xdd, 0xbf, 0xaa, 0xd0, 0x41,
	0x61, 0xed, 0xfc, 0x4b, 0x16, 0xf8, 0x84, 0x3a, 0x8d, 0x55, 0xb6, 0xb6, 0x50, 0x65, 0xf7, 0xa0,
	0xa3, 0x07, 0x7a, 0x28, 0x2e, 0xe5, 0x2a, 0x06, 0xbb, 0xcd, 0x67, 0x41, 0x3e, 0xa5, 0x53, 0xf2,
	0x10, 0xba, 0x06, 0xf3, 0x8a, 0xb1, 0xf7, 0x58, 0x4e, 0xea, 0xde, 0x86, 0x46, 0xfd, 0x91, 0xb1,
	0xf7, 0x22, 0xeb, 0x0c, 0xae, 0x2c, 0x00, 0x0d, 0x99, 0x75, 0x1a, 0xf9, 0xa5, 0xc0, 0xdd, 0x13,
	0xb0, 0x5e, 0xd2, 0x9c, 0xb3, 0xec, 0x75, 0x16, 0xb0, 0x6c, 0x31, 0xbe, 0xe2, 0xfe, 0xc4, 0x48,
	0x18, 0xa6, 0x82, 0xa1, 0xce, 0x69, 0xc5, 0x33, 0x23, 0xf7, 0x8f, 0x1a, 0xd8, 0xe8, 0x30, 0x99,
	0x04, 0xcb, 0xae, 0xc2, 0x2e, 0xd8, 0x14, 0x27, 0x8d, 0x4b, 0x60, 0x49, 0x4c, 0xe6, 0xff, 0x36,
	0xa8, 0xe1, 0xe3, 0x61, 0x94, 0x5c, 0xa8, 0xa8, 0x80, 0x82, 0xce, 0x92, 0x0b, 0x83, 0x40, 0x39,
	0x7a, 0x4a, 0x23, 0x50, 0x4d, 0x61, 0x1f, 0x15, 0xea, 0x3a, 0x61, 0xdf, 0x50, 0xd8, 0x47, 0x85,
	0x86, 0x49, 0xd0, 0x15, 0x0e, 0x50, 0x61, 0x4d, 0x27, 0x1c, 0x18, 0x0a, 0x07, 0xa8, 0xd0, 0x34,
	0x09, 0xba, 0xc2, 0x21, 0x2a, 0xac, 0xeb, 0x84, 0x43, 0x43, 0xe1, 0x10, 0x15, 0xc0, 0x24, 0xe8,
	0x0a, 0x47, 0xa8, 0x60, 0xe9, 0x84, 0x23, 0x43, 0xe1, 0x08, 0x15, 0x6c, 0x93, 0xa0, 0x2b, 0x1c,
	0xa3, 0x42, 0x4b, 0x27, 0x1c, 0x1b, 0x0a, 0xc7, 0xa8, 0xd0, 0x36, 0x09, 0x94, 0xbb, 0x3f, 0x15,
	0xa5, 0xcd, 0xa3, 0xc9, 0x05, 0x23, 0x5f, 0xc0, 0x46, 0xf9, 0x8e, 0x0e, 0x73, 0x4e, 0x33, 0xae,
	0x5e, 0xd3, 0x56, 0xf1, 0x9a, 0x0e, 0x04, 0x48, 0x5c, 0x68, 0xcd, 0x78, 0x2c, 0x91, 0x0f, 0x6b,
	0xad, 0x2c, 0xb6, 0xc1, 0xf7, 0x49, 0xe0, 0x3e, 0x81, 0x8e, 0x26, 0x5d, 0x16, 0xae, 0x4c, 0x8c,
	0xe6, 0x0b, 0x17, 0x82, 0x5a, 0xe1, 0xd2, 0x0c, 0x07, 0x61, 0xb0, 0x98, 0x66, 0x07, 0x7f, 0xae,
	0x43, 0x43, 0x92, 0xc8, 0x29, 0x10, 0x6f, 0x14, 0x26, 0x69, 0x1f, 0xdb, 0x63, 0xd5, 0x4a, 0x93,
	0xad, 0x47, 0xea, 0xb7, 0x8a, 0xf9, 0xcb, 0xa4, 0x77, 0x67, 0x01, 0x1f, 0x47, 0x53, 0xb7, 0x42,
	0xbe, 0x06, 0x40, 0x15, 0xec, 0x86, 0x49, 0xc9, 0xd2, 0x5b, 0xec, 0x1e, 0x99, 0x43, 0xa5, 0xe5,
	0x29, 0x6c, 0xca, 0xf5, 0x47, 0x62, 0xbb, 0x45, 0x93, 0x42, 0xee, 0x15, 0xe4, 0xb9, 0xae, 0xe8,
	0x1a, 0x95, 0x23, 0x68, 0x8a, 0x52, 0x28, 0x1a, 0x48, 0xb2, 0x59, 0x30, 0xb4, 0x86, 0xb3, 0xd7,
	0x35, 0x41, 0x69, 0xd5, 0x87, 0xae, 0x18, 0xde, 0xee, 0xe8, 0x4f, 0x64, 0xdf, 0xfa, 0xe9, 0x27,
	0xef, 0x03, 0xc1, 0xd5, 0x6f, 0x75, 0xf0, 0x6f, 0xc1, 0x96, 0x6f, 0xb2, 0x0a, 0xe7, 0xdd, 0x82,
	0x65, 0x74, 0x78, 0xbd, 0xd2, 0x27, 0xda, 0x03, 0xee, 0x56, 0xc8, 0x77, 0xd0, 0x1d, 0x4c, 0xde,
	0xc6, 0x21, 0xd7, 0x1f, 0xe8, 0x4d, 0x53, 0x02, 0xc1, 0xd9, 0xea, 0xb3, 0x77, 0xd4, 0xad, 0x90,
	0x6f, 0xa0, 0x5d, 0x3c, 0x2d, 0x52, 0x87, 0x74, 0x4a, 0x9e, 0xc2, 0x67, 0x4b, 0x6b, 0xf5, 0x13,
	0x37, 0xde, 0xd5, 0x6a, 0xe1, 0xa7, 0x5b, 0xb7, 0x24, 0xe0, 0x31, 0x9f, 0x85, 0x97, 0x5a, 0xd0,
	0x35, 0x5e, 0x6f, 0x41, 0xce, 0xad, 0xec, 0x55, 0x1f, 0x57, 0x85, 0xd3, 0xd4, 0xdb, 0x4e, 0xf1,
	0x57, 0x4c, 0x19, 0x72, 0xf3, 0xc5, 0x5f, 0x66, 0xff, 0xb8, 0x4a, 0x5e, 0xc3, 0xc6, 0xdc, 0xab,
	0x4f, 0x3e, 0xd7, 0x05, 0x16, 0xdb, 0x81, 0x9e, 0x63, 0x08, 0x69, 0x04, 0x14, 0x7c, 0x0a, 0xd6,
	0xac, 0x35, 0xc8, 0xc9, 0xff, 0x74, 0x31, 0xa3, 0x5f, 0x98, 0xe5, 0xa0, 0xfe, 0x8c, 0xb8, 0x15,
	0xf2, 0x5c, 0x6e, 0x49, 0x8f, 0xa2, 0xb1, 0xa5, 0xc5, 0x76, 0xa2, 0xb7, 0x2c, 0xca, 0x6e, 0x85,
	0x9c, 0x00, 0xcc, 0x0c, 0xcc, 0xad, 0x18, 0x7d, 0x46, 0x6f, 0x79, 0xa2, 0xe1, 0x79, 0x9e, 0x41,
	0x7b, 0xc0, 0xb8, 0x5e, 0x18, 0xe7, 0x16, 0x43, 0x70, 0xe6, 0x94, 0xf9, 0x3a, 0xe7, 0x56, 0xc8,
	0x53, 0xfd, 0x40, 0x52, 0x63, 0x6b, 0x09, 0x7d, 0x10, 0x06, 0xbd, 0x65, 0xda, 0x6e, 0xe5, 0x64,
	0x07, 0x36, 0xc2, 0xf4, 0x91, 0x3f, 0x0a, 0x7f, 0x0e, 0x15, 0xe1, 0x44, 0xd5, 0xea, 0xf3, 0x2c,
	0xe5, 0xe9, 0x79, 0xf5, 0x6d, 0x03, 0xff, 0x87, 0x39, 0xfc, 0x27, 0x00, 0x00, 0xff, 0xff, 0xb9,
	0x5d, 0x4c, 0xe8, 0x97, 0x11, 0x00, 0x00,
}
