// Code generated by protoc-gen-go.
// source: ticket.proto
// DO NOT EDIT!

/*
Package ticket is a generated protocol buffer package.

It is generated from these files:
	ticket.proto

It has these top-level messages:
	AccountRequest
	AccountReply
	LoginRequest
	LoginReply
	TicketRequest
	TicketReply
*/
package ticket

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AccountRequest struct {
	UserId         string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Password       string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	PoliceName     string `protobuf:"bytes,3,opt,name=police_name,json=policeName" json:"police_name,omitempty"`
	PoliceType     string `protobuf:"bytes,4,opt,name=police_type,json=policeType" json:"police_type,omitempty"`
	PoliceCity     string `protobuf:"bytes,5,opt,name=police_city,json=policeCity" json:"police_city,omitempty"`
	PoliceDept     string `protobuf:"bytes,6,opt,name=police_dept,json=policeDept" json:"police_dept,omitempty"`
	PoliceStation  string `protobuf:"bytes,7,opt,name=police_station,json=policeStation" json:"police_station,omitempty"`
	PolicePortrait []byte `protobuf:"bytes,8,opt,name=police_portrait,json=policePortrait,proto3" json:"police_portrait,omitempty"`
}

func (m *AccountRequest) Reset()                    { *m = AccountRequest{} }
func (m *AccountRequest) String() string            { return proto.CompactTextString(m) }
func (*AccountRequest) ProtoMessage()               {}
func (*AccountRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AccountRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *AccountRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AccountRequest) GetPoliceName() string {
	if m != nil {
		return m.PoliceName
	}
	return ""
}

func (m *AccountRequest) GetPoliceType() string {
	if m != nil {
		return m.PoliceType
	}
	return ""
}

func (m *AccountRequest) GetPoliceCity() string {
	if m != nil {
		return m.PoliceCity
	}
	return ""
}

func (m *AccountRequest) GetPoliceDept() string {
	if m != nil {
		return m.PoliceDept
	}
	return ""
}

func (m *AccountRequest) GetPoliceStation() string {
	if m != nil {
		return m.PoliceStation
	}
	return ""
}

func (m *AccountRequest) GetPolicePortrait() []byte {
	if m != nil {
		return m.PolicePortrait
	}
	return nil
}

type AccountReply struct {
	CreateSuccess bool `protobuf:"varint,1,opt,name=create_success,json=createSuccess" json:"create_success,omitempty"`
}

func (m *AccountReply) Reset()                    { *m = AccountReply{} }
func (m *AccountReply) String() string            { return proto.CompactTextString(m) }
func (*AccountReply) ProtoMessage()               {}
func (*AccountReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AccountReply) GetCreateSuccess() bool {
	if m != nil {
		return m.CreateSuccess
	}
	return false
}

type LoginRequest struct {
	UserId   string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *LoginRequest) Reset()                    { *m = LoginRequest{} }
func (m *LoginRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()               {}
func (*LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *LoginRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginReply struct {
	LoginSuccess   bool   `protobuf:"varint,1,opt,name=login_success,json=loginSuccess" json:"login_success,omitempty"`
	PoliceName     string `protobuf:"bytes,2,opt,name=police_name,json=policeName" json:"police_name,omitempty"`
	PoliceType     string `protobuf:"bytes,3,opt,name=police_type,json=policeType" json:"police_type,omitempty"`
	PoliceCity     string `protobuf:"bytes,4,opt,name=police_city,json=policeCity" json:"police_city,omitempty"`
	PoliceDept     string `protobuf:"bytes,5,opt,name=police_dept,json=policeDept" json:"police_dept,omitempty"`
	PoliceStation  string `protobuf:"bytes,6,opt,name=police_station,json=policeStation" json:"police_station,omitempty"`
	PolicePortrait []byte `protobuf:"bytes,7,opt,name=police_portrait,json=policePortrait,proto3" json:"police_portrait,omitempty"`
}

func (m *LoginReply) Reset()                    { *m = LoginReply{} }
func (m *LoginReply) String() string            { return proto.CompactTextString(m) }
func (*LoginReply) ProtoMessage()               {}
func (*LoginReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *LoginReply) GetLoginSuccess() bool {
	if m != nil {
		return m.LoginSuccess
	}
	return false
}

func (m *LoginReply) GetPoliceName() string {
	if m != nil {
		return m.PoliceName
	}
	return ""
}

func (m *LoginReply) GetPoliceType() string {
	if m != nil {
		return m.PoliceType
	}
	return ""
}

func (m *LoginReply) GetPoliceCity() string {
	if m != nil {
		return m.PoliceCity
	}
	return ""
}

func (m *LoginReply) GetPoliceDept() string {
	if m != nil {
		return m.PoliceDept
	}
	return ""
}

func (m *LoginReply) GetPoliceStation() string {
	if m != nil {
		return m.PoliceStation
	}
	return ""
}

func (m *LoginReply) GetPolicePortrait() []byte {
	if m != nil {
		return m.PolicePortrait
	}
	return nil
}

type TicketRequest struct {
	TicketId       int64   `protobuf:"varint,1,opt,name=ticket_id,json=ticketId" json:"ticket_id,omitempty"`
	UserId         string  `protobuf:"bytes,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	LicenseNum     string  `protobuf:"bytes,3,opt,name=license_num,json=licenseNum" json:"license_num,omitempty"`
	LicenseColor   string  `protobuf:"bytes,4,opt,name=license_color,json=licenseColor" json:"license_color,omitempty"`
	LicenseCorrect bool    `protobuf:"varint,5,opt,name=license_correct,json=licenseCorrect" json:"license_correct,omitempty"`
	VehicleType    string  `protobuf:"bytes,6,opt,name=vehicle_type,json=vehicleType" json:"vehicle_type,omitempty"`
	VehicleColor   string  `protobuf:"bytes,7,opt,name=vehicle_color,json=vehicleColor" json:"vehicle_color,omitempty"`
	Year           int32   `protobuf:"varint,8,opt,name=year" json:"year,omitempty"`
	Month          int32   `protobuf:"varint,9,opt,name=month" json:"month,omitempty"`
	Day            int32   `protobuf:"varint,10,opt,name=day" json:"day,omitempty"`
	Hour           int32   `protobuf:"varint,11,opt,name=hour" json:"hour,omitempty"`
	Minute         int32   `protobuf:"varint,12,opt,name=minute" json:"minute,omitempty"`
	Address        string  `protobuf:"bytes,13,opt,name=address" json:"address,omitempty"`
	Longitude      float64 `protobuf:"fixed64,14,opt,name=longitude" json:"longitude,omitempty"`
	Latitude       float64 `protobuf:"fixed64,15,opt,name=latitude" json:"latitude,omitempty"`
	MapImage       []byte  `protobuf:"bytes,16,opt,name=map_image,json=mapImage,proto3" json:"map_image,omitempty"`
	FarImage       []byte  `protobuf:"bytes,17,opt,name=far_image,json=farImage,proto3" json:"far_image,omitempty"`
	CloseImage     []byte  `protobuf:"bytes,18,opt,name=close_image,json=closeImage,proto3" json:"close_image,omitempty"`
	TicketImage    []byte  `protobuf:"bytes,19,opt,name=ticket_image,json=ticketImage,proto3" json:"ticket_image,omitempty"`
}

func (m *TicketRequest) Reset()                    { *m = TicketRequest{} }
func (m *TicketRequest) String() string            { return proto.CompactTextString(m) }
func (*TicketRequest) ProtoMessage()               {}
func (*TicketRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *TicketRequest) GetTicketId() int64 {
	if m != nil {
		return m.TicketId
	}
	return 0
}

func (m *TicketRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *TicketRequest) GetLicenseNum() string {
	if m != nil {
		return m.LicenseNum
	}
	return ""
}

func (m *TicketRequest) GetLicenseColor() string {
	if m != nil {
		return m.LicenseColor
	}
	return ""
}

func (m *TicketRequest) GetLicenseCorrect() bool {
	if m != nil {
		return m.LicenseCorrect
	}
	return false
}

func (m *TicketRequest) GetVehicleType() string {
	if m != nil {
		return m.VehicleType
	}
	return ""
}

func (m *TicketRequest) GetVehicleColor() string {
	if m != nil {
		return m.VehicleColor
	}
	return ""
}

func (m *TicketRequest) GetYear() int32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *TicketRequest) GetMonth() int32 {
	if m != nil {
		return m.Month
	}
	return 0
}

func (m *TicketRequest) GetDay() int32 {
	if m != nil {
		return m.Day
	}
	return 0
}

func (m *TicketRequest) GetHour() int32 {
	if m != nil {
		return m.Hour
	}
	return 0
}

func (m *TicketRequest) GetMinute() int32 {
	if m != nil {
		return m.Minute
	}
	return 0
}

func (m *TicketRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *TicketRequest) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *TicketRequest) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *TicketRequest) GetMapImage() []byte {
	if m != nil {
		return m.MapImage
	}
	return nil
}

func (m *TicketRequest) GetFarImage() []byte {
	if m != nil {
		return m.FarImage
	}
	return nil
}

func (m *TicketRequest) GetCloseImage() []byte {
	if m != nil {
		return m.CloseImage
	}
	return nil
}

func (m *TicketRequest) GetTicketImage() []byte {
	if m != nil {
		return m.TicketImage
	}
	return nil
}

type TicketReply struct {
	RecordSuccess bool `protobuf:"varint,1,opt,name=record_success,json=recordSuccess" json:"record_success,omitempty"`
}

func (m *TicketReply) Reset()                    { *m = TicketReply{} }
func (m *TicketReply) String() string            { return proto.CompactTextString(m) }
func (*TicketReply) ProtoMessage()               {}
func (*TicketReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *TicketReply) GetRecordSuccess() bool {
	if m != nil {
		return m.RecordSuccess
	}
	return false
}

func init() {
	proto.RegisterType((*AccountRequest)(nil), "ticket.AccountRequest")
	proto.RegisterType((*AccountReply)(nil), "ticket.AccountReply")
	proto.RegisterType((*LoginRequest)(nil), "ticket.LoginRequest")
	proto.RegisterType((*LoginReply)(nil), "ticket.LoginReply")
	proto.RegisterType((*TicketRequest)(nil), "ticket.TicketRequest")
	proto.RegisterType((*TicketReply)(nil), "ticket.TicketReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Ticket service

type TicketClient interface {
	CreateAccount(ctx context.Context, in *AccountRequest, opts ...grpc.CallOption) (*AccountReply, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error)
	RecordTicket(ctx context.Context, in *TicketRequest, opts ...grpc.CallOption) (*TicketReply, error)
}

type ticketClient struct {
	cc *grpc.ClientConn
}

func NewTicketClient(cc *grpc.ClientConn) TicketClient {
	return &ticketClient{cc}
}

func (c *ticketClient) CreateAccount(ctx context.Context, in *AccountRequest, opts ...grpc.CallOption) (*AccountReply, error) {
	out := new(AccountReply)
	err := grpc.Invoke(ctx, "/ticket.Ticket/CreateAccount", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error) {
	out := new(LoginReply)
	err := grpc.Invoke(ctx, "/ticket.Ticket/Login", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketClient) RecordTicket(ctx context.Context, in *TicketRequest, opts ...grpc.CallOption) (*TicketReply, error) {
	out := new(TicketReply)
	err := grpc.Invoke(ctx, "/ticket.Ticket/RecordTicket", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Ticket service

type TicketServer interface {
	CreateAccount(context.Context, *AccountRequest) (*AccountReply, error)
	Login(context.Context, *LoginRequest) (*LoginReply, error)
	RecordTicket(context.Context, *TicketRequest) (*TicketReply, error)
}

func RegisterTicketServer(s *grpc.Server, srv TicketServer) {
	s.RegisterService(&_Ticket_serviceDesc, srv)
}

func _Ticket_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ticket.Ticket/CreateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServer).CreateAccount(ctx, req.(*AccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ticket_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ticket.Ticket/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ticket_RecordTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TicketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServer).RecordTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ticket.Ticket/RecordTicket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServer).RecordTicket(ctx, req.(*TicketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Ticket_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ticket.Ticket",
	HandlerType: (*TicketServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAccount",
			Handler:    _Ticket_CreateAccount_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _Ticket_Login_Handler,
		},
		{
			MethodName: "RecordTicket",
			Handler:    _Ticket_RecordTicket_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ticket.proto",
}

func init() { proto.RegisterFile("ticket.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 657 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc7, 0x71, 0x3e, 0x9c, 0x64, 0x6c, 0xa7, 0x65, 0x5b, 0xca, 0x2a, 0x20, 0x35, 0x75, 0x85,
	0xe8, 0xa9, 0x07, 0x0a, 0x37, 0x24, 0x44, 0xc3, 0xa5, 0x12, 0xaa, 0x2a, 0xb7, 0xf7, 0x68, 0x59,
	0x6f, 0x9b, 0x15, 0xb6, 0xd7, 0xac, 0xd7, 0x20, 0x73, 0xe7, 0x21, 0x78, 0x11, 0x4e, 0x3c, 0x1c,
	0xda, 0x0f, 0xa7, 0x6e, 0x40, 0x6a, 0x25, 0x6e, 0x9e, 0xdf, 0xfc, 0xc7, 0x6b, 0xff, 0x67, 0x76,
	0x20, 0x54, 0x9c, 0x7e, 0x66, 0xea, 0xb8, 0x94, 0x42, 0x09, 0xe4, 0xdb, 0x28, 0xfe, 0xd9, 0x83,
	0xe9, 0x7b, 0x4a, 0x45, 0x5d, 0xa8, 0x84, 0x7d, 0xa9, 0x59, 0xa5, 0xd0, 0x53, 0x18, 0xd5, 0x15,
	0x93, 0x4b, 0x9e, 0x62, 0x6f, 0xee, 0x1d, 0x4d, 0x12, 0x5f, 0x87, 0x67, 0x29, 0x9a, 0xc1, 0xb8,
	0x24, 0x55, 0xf5, 0x4d, 0xc8, 0x14, 0xf7, 0x4c, 0x66, 0x1d, 0xa3, 0x7d, 0x08, 0x4a, 0x91, 0x71,
	0xca, 0x96, 0x05, 0xc9, 0x19, 0xee, 0x9b, 0x34, 0x58, 0x74, 0x4e, 0x72, 0xd6, 0x11, 0xa8, 0xa6,
	0x64, 0x78, 0xd0, 0x15, 0x5c, 0x35, 0x65, 0x57, 0x40, 0xb9, 0x6a, 0xf0, 0xb0, 0x2b, 0x58, 0x70,
	0xd5, 0x74, 0x04, 0x29, 0x2b, 0x15, 0xf6, 0xbb, 0x82, 0x0f, 0xac, 0x54, 0xe8, 0x05, 0x4c, 0x9d,
	0xa0, 0x52, 0x44, 0x71, 0x51, 0xe0, 0x91, 0xd1, 0x44, 0x96, 0x5e, 0x5a, 0x88, 0x5e, 0xc2, 0x96,
	0x93, 0x95, 0x42, 0x2a, 0x49, 0xb8, 0xc2, 0xe3, 0xb9, 0x77, 0x14, 0x26, 0xae, 0xfa, 0xc2, 0xd1,
	0xf8, 0x0d, 0x84, 0x6b, 0x6b, 0xca, 0xac, 0xd1, 0xef, 0xa7, 0x92, 0x11, 0xc5, 0x96, 0x55, 0x4d,
	0x29, 0xab, 0x2a, 0xe3, 0xcf, 0x38, 0x89, 0x2c, 0xbd, 0xb4, 0x30, 0x5e, 0x40, 0xf8, 0x51, 0xdc,
	0xf0, 0xe2, 0x7f, 0xfc, 0x8c, 0x7f, 0xf4, 0x00, 0xdc, 0x5b, 0xf4, 0xd1, 0x87, 0x10, 0x65, 0x3a,
	0xda, 0x38, 0x39, 0x34, 0xd0, 0x1d, 0xbc, 0xd9, 0x83, 0xde, 0x7d, 0x3d, 0xe8, 0xdf, 0xd7, 0x83,
	0xc1, 0x7d, 0x3d, 0x18, 0x3e, 0xa0, 0x07, 0xfe, 0x03, 0x7b, 0x30, 0xfa, 0x67, 0x0f, 0x7e, 0x0d,
	0x20, 0xba, 0x32, 0xa3, 0xda, 0xda, 0xf9, 0x0c, 0x26, 0x76, 0x76, 0x5b, 0x43, 0xfb, 0xc9, 0xd8,
	0x82, 0xb3, 0xb4, 0xeb, 0x75, 0xef, 0x8e, 0xd7, 0xfb, 0x10, 0xe8, 0xf7, 0x16, 0x15, 0x5b, 0x16,
	0x75, 0xde, 0xfe, 0xba, 0x43, 0xe7, 0x75, 0x6e, 0x1c, 0x76, 0x02, 0x2a, 0x32, 0x21, 0xdd, 0xcf,
	0x87, 0x0e, 0x2e, 0x34, 0xd3, 0x9f, 0x7d, 0x2b, 0x92, 0x92, 0x51, 0x6b, 0xc1, 0x38, 0x99, 0xae,
	0x65, 0x86, 0xa2, 0x03, 0x08, 0xbf, 0xb2, 0x15, 0xa7, 0x99, 0xb3, 0xda, 0x9a, 0x10, 0x38, 0x66,
	0xbc, 0x3e, 0x84, 0xa8, 0x95, 0xd8, 0x03, 0xed, 0xb0, 0xb6, 0x75, 0xf6, 0x40, 0x04, 0x83, 0x86,
	0x11, 0x69, 0x06, 0x74, 0x98, 0x98, 0x67, 0xb4, 0x0b, 0xc3, 0x5c, 0x14, 0x6a, 0x85, 0x27, 0x06,
	0xda, 0x00, 0x6d, 0x43, 0x3f, 0x25, 0x0d, 0x06, 0xc3, 0xf4, 0xa3, 0xae, 0x5d, 0x89, 0x5a, 0xe2,
	0xc0, 0xd6, 0xea, 0x67, 0xb4, 0x07, 0x7e, 0xce, 0x8b, 0x5a, 0x31, 0x1c, 0x1a, 0xea, 0x22, 0x84,
	0x61, 0x44, 0xd2, 0x54, 0xea, 0xc9, 0x8a, 0xcc, 0x67, 0xb4, 0x21, 0x7a, 0x0e, 0x93, 0x4c, 0x14,
	0x37, 0x5c, 0xd5, 0x29, 0xc3, 0xd3, 0xb9, 0x77, 0xe4, 0x25, 0xb7, 0x40, 0x8f, 0x70, 0x46, 0x94,
	0x4d, 0x6e, 0x99, 0xe4, 0x3a, 0xd6, 0x8d, 0xca, 0x49, 0xb9, 0xe4, 0x39, 0xb9, 0x61, 0x78, 0xdb,
	0x74, 0x77, 0x9c, 0x93, 0xf2, 0x4c, 0xc7, 0x3a, 0x79, 0x4d, 0xa4, 0x4b, 0x3e, 0xb6, 0xc9, 0x6b,
	0x22, 0x6d, 0x72, 0x1f, 0x02, 0x9a, 0x89, 0x8a, 0xb9, 0x34, 0x32, 0x69, 0x30, 0xc8, 0x0a, 0x0e,
	0xda, 0x6d, 0xe6, 0x14, 0x3b, 0x46, 0x11, 0xb8, 0x31, 0xd0, 0x28, 0x7e, 0x0d, 0x41, 0x3b, 0x37,
	0xee, 0xee, 0x4a, 0x46, 0x85, 0x4c, 0x37, 0xef, 0xae, 0xa5, 0xee, 0x0a, 0xbd, 0xfa, 0xed, 0x81,
	0x6f, 0xcb, 0xd0, 0x3b, 0x88, 0x16, 0xe6, 0x5e, 0xbb, 0x1d, 0x80, 0xf6, 0x8e, 0xdd, 0x06, 0xbd,
	0xbb, 0x2f, 0x67, 0xbb, 0x7f, 0xf1, 0x32, 0x6b, 0xe2, 0x47, 0xe8, 0x04, 0x86, 0xe6, 0x06, 0xa3,
	0xb5, 0xa0, 0xbb, 0x16, 0x66, 0x68, 0x83, 0xda, 0xa2, 0xb7, 0x10, 0x26, 0xe6, 0x8b, 0xdc, 0x57,
	0x3c, 0x69, 0x55, 0x77, 0x2e, 0xc1, 0x6c, 0x67, 0x13, 0x9b, 0xea, 0xd3, 0x39, 0x6c, 0x71, 0x71,
	0x4c, 0x57, 0xfc, 0x3b, 0x77, 0x82, 0x53, 0xe7, 0xc2, 0x85, 0xde, 0xfa, 0x17, 0xde, 0x27, 0xdf,
	0xac, 0xff, 0x93, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x72, 0x8d, 0x43, 0xfb, 0x0e, 0x06, 0x00,
	0x00,
}
