// Code generated by protoc-gen-go.
// source: ticket.proto
// DO NOT EDIT!

/*
Package ticket is a generated protocol buffer package.

It is generated from these files:
	ticket.proto

It has these top-level messages:
	AccountRequest
	AccountReply
	LoginRequest
	LoginReply
	TicketRequest
	TicketReply
	SlaveLoc
	MasterOrder
*/
package ticket

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AccountRequest struct {
	UserId         string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Password       string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	PoliceName     string `protobuf:"bytes,3,opt,name=police_name,json=policeName" json:"police_name,omitempty"`
	PoliceType     string `protobuf:"bytes,4,opt,name=police_type,json=policeType" json:"police_type,omitempty"`
	PoliceCity     string `protobuf:"bytes,5,opt,name=police_city,json=policeCity" json:"police_city,omitempty"`
	PoliceDept     string `protobuf:"bytes,6,opt,name=police_dept,json=policeDept" json:"police_dept,omitempty"`
	PoliceStation  string `protobuf:"bytes,7,opt,name=police_station,json=policeStation" json:"police_station,omitempty"`
	PolicePortrait []byte `protobuf:"bytes,8,opt,name=police_portrait,json=policePortrait,proto3" json:"police_portrait,omitempty"`
}

func (m *AccountRequest) Reset()                    { *m = AccountRequest{} }
func (m *AccountRequest) String() string            { return proto.CompactTextString(m) }
func (*AccountRequest) ProtoMessage()               {}
func (*AccountRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AccountRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *AccountRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AccountRequest) GetPoliceName() string {
	if m != nil {
		return m.PoliceName
	}
	return ""
}

func (m *AccountRequest) GetPoliceType() string {
	if m != nil {
		return m.PoliceType
	}
	return ""
}

func (m *AccountRequest) GetPoliceCity() string {
	if m != nil {
		return m.PoliceCity
	}
	return ""
}

func (m *AccountRequest) GetPoliceDept() string {
	if m != nil {
		return m.PoliceDept
	}
	return ""
}

func (m *AccountRequest) GetPoliceStation() string {
	if m != nil {
		return m.PoliceStation
	}
	return ""
}

func (m *AccountRequest) GetPolicePortrait() []byte {
	if m != nil {
		return m.PolicePortrait
	}
	return nil
}

type AccountReply struct {
	CreateSuccess bool `protobuf:"varint,1,opt,name=create_success,json=createSuccess" json:"create_success,omitempty"`
}

func (m *AccountReply) Reset()                    { *m = AccountReply{} }
func (m *AccountReply) String() string            { return proto.CompactTextString(m) }
func (*AccountReply) ProtoMessage()               {}
func (*AccountReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AccountReply) GetCreateSuccess() bool {
	if m != nil {
		return m.CreateSuccess
	}
	return false
}

type LoginRequest struct {
	UserId   string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *LoginRequest) Reset()                    { *m = LoginRequest{} }
func (m *LoginRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()               {}
func (*LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *LoginRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginReply struct {
	LoginSuccess   bool   `protobuf:"varint,1,opt,name=login_success,json=loginSuccess" json:"login_success,omitempty"`
	PoliceName     string `protobuf:"bytes,2,opt,name=police_name,json=policeName" json:"police_name,omitempty"`
	PoliceType     string `protobuf:"bytes,3,opt,name=police_type,json=policeType" json:"police_type,omitempty"`
	PoliceCity     string `protobuf:"bytes,4,opt,name=police_city,json=policeCity" json:"police_city,omitempty"`
	PoliceDept     string `protobuf:"bytes,5,opt,name=police_dept,json=policeDept" json:"police_dept,omitempty"`
	PoliceStation  string `protobuf:"bytes,6,opt,name=police_station,json=policeStation" json:"police_station,omitempty"`
	PolicePortrait []byte `protobuf:"bytes,7,opt,name=police_portrait,json=policePortrait,proto3" json:"police_portrait,omitempty"`
}

func (m *LoginReply) Reset()                    { *m = LoginReply{} }
func (m *LoginReply) String() string            { return proto.CompactTextString(m) }
func (*LoginReply) ProtoMessage()               {}
func (*LoginReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *LoginReply) GetLoginSuccess() bool {
	if m != nil {
		return m.LoginSuccess
	}
	return false
}

func (m *LoginReply) GetPoliceName() string {
	if m != nil {
		return m.PoliceName
	}
	return ""
}

func (m *LoginReply) GetPoliceType() string {
	if m != nil {
		return m.PoliceType
	}
	return ""
}

func (m *LoginReply) GetPoliceCity() string {
	if m != nil {
		return m.PoliceCity
	}
	return ""
}

func (m *LoginReply) GetPoliceDept() string {
	if m != nil {
		return m.PoliceDept
	}
	return ""
}

func (m *LoginReply) GetPoliceStation() string {
	if m != nil {
		return m.PoliceStation
	}
	return ""
}

func (m *LoginReply) GetPolicePortrait() []byte {
	if m != nil {
		return m.PolicePortrait
	}
	return nil
}

type TicketRequest struct {
	TicketId       int64   `protobuf:"varint,1,opt,name=ticket_id,json=ticketId" json:"ticket_id,omitempty"`
	UserId         string  `protobuf:"bytes,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	LicenseNum     string  `protobuf:"bytes,3,opt,name=license_num,json=licenseNum" json:"license_num,omitempty"`
	LicenseColor   string  `protobuf:"bytes,4,opt,name=license_color,json=licenseColor" json:"license_color,omitempty"`
	LicenseCorrect bool    `protobuf:"varint,5,opt,name=license_correct,json=licenseCorrect" json:"license_correct,omitempty"`
	VehicleType    string  `protobuf:"bytes,6,opt,name=vehicle_type,json=vehicleType" json:"vehicle_type,omitempty"`
	VehicleColor   string  `protobuf:"bytes,7,opt,name=vehicle_color,json=vehicleColor" json:"vehicle_color,omitempty"`
	Year           int32   `protobuf:"varint,8,opt,name=year" json:"year,omitempty"`
	Month          int32   `protobuf:"varint,9,opt,name=month" json:"month,omitempty"`
	Day            int32   `protobuf:"varint,10,opt,name=day" json:"day,omitempty"`
	Hour           int32   `protobuf:"varint,11,opt,name=hour" json:"hour,omitempty"`
	Minute         int32   `protobuf:"varint,12,opt,name=minute" json:"minute,omitempty"`
	Address        string  `protobuf:"bytes,13,opt,name=address" json:"address,omitempty"`
	Longitude      float64 `protobuf:"fixed64,14,opt,name=longitude" json:"longitude,omitempty"`
	Latitude       float64 `protobuf:"fixed64,15,opt,name=latitude" json:"latitude,omitempty"`
	MapImage       []byte  `protobuf:"bytes,16,opt,name=map_image,json=mapImage,proto3" json:"map_image,omitempty"`
	FarImage       []byte  `protobuf:"bytes,17,opt,name=far_image,json=farImage,proto3" json:"far_image,omitempty"`
	CloseImage     []byte  `protobuf:"bytes,18,opt,name=close_image,json=closeImage,proto3" json:"close_image,omitempty"`
	TicketImage    []byte  `protobuf:"bytes,19,opt,name=ticket_image,json=ticketImage,proto3" json:"ticket_image,omitempty"`
}

func (m *TicketRequest) Reset()                    { *m = TicketRequest{} }
func (m *TicketRequest) String() string            { return proto.CompactTextString(m) }
func (*TicketRequest) ProtoMessage()               {}
func (*TicketRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *TicketRequest) GetTicketId() int64 {
	if m != nil {
		return m.TicketId
	}
	return 0
}

func (m *TicketRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *TicketRequest) GetLicenseNum() string {
	if m != nil {
		return m.LicenseNum
	}
	return ""
}

func (m *TicketRequest) GetLicenseColor() string {
	if m != nil {
		return m.LicenseColor
	}
	return ""
}

func (m *TicketRequest) GetLicenseCorrect() bool {
	if m != nil {
		return m.LicenseCorrect
	}
	return false
}

func (m *TicketRequest) GetVehicleType() string {
	if m != nil {
		return m.VehicleType
	}
	return ""
}

func (m *TicketRequest) GetVehicleColor() string {
	if m != nil {
		return m.VehicleColor
	}
	return ""
}

func (m *TicketRequest) GetYear() int32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *TicketRequest) GetMonth() int32 {
	if m != nil {
		return m.Month
	}
	return 0
}

func (m *TicketRequest) GetDay() int32 {
	if m != nil {
		return m.Day
	}
	return 0
}

func (m *TicketRequest) GetHour() int32 {
	if m != nil {
		return m.Hour
	}
	return 0
}

func (m *TicketRequest) GetMinute() int32 {
	if m != nil {
		return m.Minute
	}
	return 0
}

func (m *TicketRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *TicketRequest) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *TicketRequest) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *TicketRequest) GetMapImage() []byte {
	if m != nil {
		return m.MapImage
	}
	return nil
}

func (m *TicketRequest) GetFarImage() []byte {
	if m != nil {
		return m.FarImage
	}
	return nil
}

func (m *TicketRequest) GetCloseImage() []byte {
	if m != nil {
		return m.CloseImage
	}
	return nil
}

func (m *TicketRequest) GetTicketImage() []byte {
	if m != nil {
		return m.TicketImage
	}
	return nil
}

type TicketReply struct {
	RecordSuccess bool `protobuf:"varint,1,opt,name=record_success,json=recordSuccess" json:"record_success,omitempty"`
}

func (m *TicketReply) Reset()                    { *m = TicketReply{} }
func (m *TicketReply) String() string            { return proto.CompactTextString(m) }
func (*TicketReply) ProtoMessage()               {}
func (*TicketReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *TicketReply) GetRecordSuccess() bool {
	if m != nil {
		return m.RecordSuccess
	}
	return false
}

type SlaveLoc struct {
	Sid       string  `protobuf:"bytes,1,opt,name=sid" json:"sid,omitempty"`
	Longitude float64 `protobuf:"fixed64,2,opt,name=longitude" json:"longitude,omitempty"`
	Latitude  float64 `protobuf:"fixed64,3,opt,name=latitude" json:"latitude,omitempty"`
}

func (m *SlaveLoc) Reset()                    { *m = SlaveLoc{} }
func (m *SlaveLoc) String() string            { return proto.CompactTextString(m) }
func (*SlaveLoc) ProtoMessage()               {}
func (*SlaveLoc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *SlaveLoc) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *SlaveLoc) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *SlaveLoc) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

type MasterOrder struct {
	Mid         string `protobuf:"bytes,1,opt,name=mid" json:"mid,omitempty"`
	MasterOrder string `protobuf:"bytes,2,opt,name=master_order,json=masterOrder" json:"master_order,omitempty"`
}

func (m *MasterOrder) Reset()                    { *m = MasterOrder{} }
func (m *MasterOrder) String() string            { return proto.CompactTextString(m) }
func (*MasterOrder) ProtoMessage()               {}
func (*MasterOrder) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *MasterOrder) GetMid() string {
	if m != nil {
		return m.Mid
	}
	return ""
}

func (m *MasterOrder) GetMasterOrder() string {
	if m != nil {
		return m.MasterOrder
	}
	return ""
}

func init() {
	proto.RegisterType((*AccountRequest)(nil), "ticket.AccountRequest")
	proto.RegisterType((*AccountReply)(nil), "ticket.AccountReply")
	proto.RegisterType((*LoginRequest)(nil), "ticket.LoginRequest")
	proto.RegisterType((*LoginReply)(nil), "ticket.LoginReply")
	proto.RegisterType((*TicketRequest)(nil), "ticket.TicketRequest")
	proto.RegisterType((*TicketReply)(nil), "ticket.TicketReply")
	proto.RegisterType((*SlaveLoc)(nil), "ticket.SlaveLoc")
	proto.RegisterType((*MasterOrder)(nil), "ticket.MasterOrder")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Ticket service

type TicketClient interface {
	RhinoCreateAccount(ctx context.Context, in *AccountRequest, opts ...grpc.CallOption) (*AccountReply, error)
	RhinoLogin(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error)
	HareCreateAccount(ctx context.Context, in *AccountRequest, opts ...grpc.CallOption) (*AccountReply, error)
	HareLogin(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error)
	RecordTicket(ctx context.Context, in *TicketRequest, opts ...grpc.CallOption) (*TicketReply, error)
	SlaveSubmit(ctx context.Context, in *SlaveLoc, opts ...grpc.CallOption) (*MasterOrder, error)
	MasterReceive(ctx context.Context, opts ...grpc.CallOption) (Ticket_MasterReceiveClient, error)
}

type ticketClient struct {
	cc *grpc.ClientConn
}

func NewTicketClient(cc *grpc.ClientConn) TicketClient {
	return &ticketClient{cc}
}

func (c *ticketClient) RhinoCreateAccount(ctx context.Context, in *AccountRequest, opts ...grpc.CallOption) (*AccountReply, error) {
	out := new(AccountReply)
	err := grpc.Invoke(ctx, "/ticket.Ticket/RhinoCreateAccount", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketClient) RhinoLogin(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error) {
	out := new(LoginReply)
	err := grpc.Invoke(ctx, "/ticket.Ticket/RhinoLogin", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketClient) HareCreateAccount(ctx context.Context, in *AccountRequest, opts ...grpc.CallOption) (*AccountReply, error) {
	out := new(AccountReply)
	err := grpc.Invoke(ctx, "/ticket.Ticket/HareCreateAccount", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketClient) HareLogin(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error) {
	out := new(LoginReply)
	err := grpc.Invoke(ctx, "/ticket.Ticket/HareLogin", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketClient) RecordTicket(ctx context.Context, in *TicketRequest, opts ...grpc.CallOption) (*TicketReply, error) {
	out := new(TicketReply)
	err := grpc.Invoke(ctx, "/ticket.Ticket/RecordTicket", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketClient) SlaveSubmit(ctx context.Context, in *SlaveLoc, opts ...grpc.CallOption) (*MasterOrder, error) {
	out := new(MasterOrder)
	err := grpc.Invoke(ctx, "/ticket.Ticket/SlaveSubmit", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketClient) MasterReceive(ctx context.Context, opts ...grpc.CallOption) (Ticket_MasterReceiveClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Ticket_serviceDesc.Streams[0], c.cc, "/ticket.Ticket/MasterReceive", opts...)
	if err != nil {
		return nil, err
	}
	x := &ticketMasterReceiveClient{stream}
	return x, nil
}

type Ticket_MasterReceiveClient interface {
	Send(*MasterOrder) error
	Recv() (*SlaveLoc, error)
	grpc.ClientStream
}

type ticketMasterReceiveClient struct {
	grpc.ClientStream
}

func (x *ticketMasterReceiveClient) Send(m *MasterOrder) error {
	return x.ClientStream.SendMsg(m)
}

func (x *ticketMasterReceiveClient) Recv() (*SlaveLoc, error) {
	m := new(SlaveLoc)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Ticket service

type TicketServer interface {
	RhinoCreateAccount(context.Context, *AccountRequest) (*AccountReply, error)
	RhinoLogin(context.Context, *LoginRequest) (*LoginReply, error)
	HareCreateAccount(context.Context, *AccountRequest) (*AccountReply, error)
	HareLogin(context.Context, *LoginRequest) (*LoginReply, error)
	RecordTicket(context.Context, *TicketRequest) (*TicketReply, error)
	SlaveSubmit(context.Context, *SlaveLoc) (*MasterOrder, error)
	MasterReceive(Ticket_MasterReceiveServer) error
}

func RegisterTicketServer(s *grpc.Server, srv TicketServer) {
	s.RegisterService(&_Ticket_serviceDesc, srv)
}

func _Ticket_RhinoCreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServer).RhinoCreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ticket.Ticket/RhinoCreateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServer).RhinoCreateAccount(ctx, req.(*AccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ticket_RhinoLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServer).RhinoLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ticket.Ticket/RhinoLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServer).RhinoLogin(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ticket_HareCreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServer).HareCreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ticket.Ticket/HareCreateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServer).HareCreateAccount(ctx, req.(*AccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ticket_HareLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServer).HareLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ticket.Ticket/HareLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServer).HareLogin(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ticket_RecordTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TicketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServer).RecordTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ticket.Ticket/RecordTicket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServer).RecordTicket(ctx, req.(*TicketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ticket_SlaveSubmit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SlaveLoc)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServer).SlaveSubmit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ticket.Ticket/SlaveSubmit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServer).SlaveSubmit(ctx, req.(*SlaveLoc))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ticket_MasterReceive_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TicketServer).MasterReceive(&ticketMasterReceiveServer{stream})
}

type Ticket_MasterReceiveServer interface {
	Send(*SlaveLoc) error
	Recv() (*MasterOrder, error)
	grpc.ServerStream
}

type ticketMasterReceiveServer struct {
	grpc.ServerStream
}

func (x *ticketMasterReceiveServer) Send(m *SlaveLoc) error {
	return x.ServerStream.SendMsg(m)
}

func (x *ticketMasterReceiveServer) Recv() (*MasterOrder, error) {
	m := new(MasterOrder)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Ticket_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ticket.Ticket",
	HandlerType: (*TicketServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RhinoCreateAccount",
			Handler:    _Ticket_RhinoCreateAccount_Handler,
		},
		{
			MethodName: "RhinoLogin",
			Handler:    _Ticket_RhinoLogin_Handler,
		},
		{
			MethodName: "HareCreateAccount",
			Handler:    _Ticket_HareCreateAccount_Handler,
		},
		{
			MethodName: "HareLogin",
			Handler:    _Ticket_HareLogin_Handler,
		},
		{
			MethodName: "RecordTicket",
			Handler:    _Ticket_RecordTicket_Handler,
		},
		{
			MethodName: "SlaveSubmit",
			Handler:    _Ticket_SlaveSubmit_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "MasterReceive",
			Handler:       _Ticket_MasterReceive_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "ticket.proto",
}

func init() { proto.RegisterFile("ticket.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 777 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xcd, 0x4e, 0xe3, 0x48,
	0x10, 0xc6, 0xf9, 0x4f, 0xd9, 0x09, 0xd0, 0xb0, 0xac, 0x95, 0x5d, 0x89, 0x60, 0xb4, 0xda, 0x9c,
	0xd0, 0x6a, 0xff, 0x0f, 0x7b, 0x59, 0xc2, 0x61, 0x91, 0x58, 0x06, 0x39, 0x68, 0xae, 0x51, 0xd3,
	0x6e, 0x48, 0x6b, 0x6c, 0xb7, 0xa7, 0xdd, 0x66, 0xe4, 0xb9, 0xcf, 0x43, 0xcc, 0x8b, 0xcc, 0x61,
	0x9e, 0x6e, 0xd4, 0x3f, 0x4e, 0x9c, 0x80, 0x06, 0x46, 0xdc, 0xba, 0xbe, 0xfa, 0xaa, 0xca, 0xfd,
	0x55, 0x75, 0x19, 0x3c, 0xc9, 0xc8, 0x1b, 0x2a, 0x4f, 0x32, 0xc1, 0x25, 0x47, 0x1d, 0x63, 0x05,
	0x1f, 0x1b, 0x30, 0xfc, 0x97, 0x10, 0x5e, 0xa4, 0x32, 0xa4, 0x6f, 0x0b, 0x9a, 0x4b, 0xf4, 0x3d,
	0x74, 0x8b, 0x9c, 0x8a, 0x39, 0x8b, 0x7c, 0x67, 0xec, 0x4c, 0xfa, 0x61, 0x47, 0x99, 0xe7, 0x11,
	0x1a, 0x41, 0x2f, 0xc3, 0x79, 0xfe, 0x8e, 0x8b, 0xc8, 0x6f, 0x68, 0xcf, 0xd2, 0x46, 0x87, 0xe0,
	0x66, 0x3c, 0x66, 0x84, 0xce, 0x53, 0x9c, 0x50, 0xbf, 0xa9, 0xdd, 0x60, 0xa0, 0x4b, 0x9c, 0xd0,
	0x1a, 0x41, 0x96, 0x19, 0xf5, 0x5b, 0x75, 0xc2, 0x75, 0x99, 0xd5, 0x09, 0x84, 0xc9, 0xd2, 0x6f,
	0xd7, 0x09, 0x53, 0x26, 0xcb, 0x1a, 0x21, 0xa2, 0x99, 0xf4, 0x3b, 0x75, 0xc2, 0x19, 0xcd, 0x24,
	0xfa, 0x09, 0x86, 0x96, 0x90, 0x4b, 0x2c, 0x19, 0x4f, 0xfd, 0xae, 0xe6, 0x0c, 0x0c, 0x3a, 0x33,
	0x20, 0xfa, 0x19, 0xb6, 0x2d, 0x2d, 0xe3, 0x42, 0x0a, 0xcc, 0xa4, 0xdf, 0x1b, 0x3b, 0x13, 0x2f,
	0xb4, 0xd1, 0x57, 0x16, 0x0d, 0xfe, 0x00, 0x6f, 0x29, 0x4d, 0x16, 0x97, 0x2a, 0x3f, 0x11, 0x14,
	0x4b, 0x3a, 0xcf, 0x0b, 0x42, 0x68, 0x9e, 0x6b, 0x7d, 0x7a, 0xe1, 0xc0, 0xa0, 0x33, 0x03, 0x06,
	0x53, 0xf0, 0x2e, 0xf8, 0x1d, 0x4b, 0x5f, 0xa2, 0x67, 0xf0, 0xa1, 0x01, 0x60, 0xb3, 0xa8, 0xd2,
	0xc7, 0x30, 0x88, 0x95, 0xb5, 0x51, 0xd9, 0xd3, 0xa0, 0x2d, 0xbc, 0xd9, 0x83, 0xc6, 0x53, 0x3d,
	0x68, 0x3e, 0xd5, 0x83, 0xd6, 0x53, 0x3d, 0x68, 0x3f, 0xa3, 0x07, 0x9d, 0x67, 0xf6, 0xa0, 0xfb,
	0x68, 0x0f, 0x3e, 0xb5, 0x60, 0x70, 0xad, 0x47, 0xb5, 0x92, 0xf3, 0x07, 0xe8, 0x9b, 0xd9, 0xad,
	0x04, 0x6d, 0x86, 0x3d, 0x03, 0x9c, 0x47, 0x75, 0xad, 0x1b, 0x6b, 0x5a, 0x1f, 0x82, 0xab, 0xf2,
	0xa6, 0x39, 0x9d, 0xa7, 0x45, 0x52, 0x5d, 0xdd, 0x42, 0x97, 0x45, 0xa2, 0x15, 0xb6, 0x04, 0xc2,
	0x63, 0x2e, 0xec, 0xe5, 0x3d, 0x0b, 0x4e, 0x15, 0xa6, 0x3e, 0x7b, 0x45, 0x12, 0x82, 0x12, 0x23,
	0x41, 0x2f, 0x1c, 0x2e, 0x69, 0x1a, 0x45, 0x47, 0xe0, 0xdd, 0xd3, 0x05, 0x23, 0xb1, 0x95, 0xda,
	0x88, 0xe0, 0x5a, 0x4c, 0x6b, 0x7d, 0x0c, 0x83, 0x8a, 0x62, 0x0a, 0x9a, 0x61, 0xad, 0xe2, 0x4c,
	0x41, 0x04, 0xad, 0x92, 0x62, 0xa1, 0x07, 0xb4, 0x1d, 0xea, 0x33, 0xda, 0x87, 0x76, 0xc2, 0x53,
	0xb9, 0xf0, 0xfb, 0x1a, 0x34, 0x06, 0xda, 0x81, 0x66, 0x84, 0x4b, 0x1f, 0x34, 0xa6, 0x8e, 0x2a,
	0x76, 0xc1, 0x0b, 0xe1, 0xbb, 0x26, 0x56, 0x9d, 0xd1, 0x01, 0x74, 0x12, 0x96, 0x16, 0x92, 0xfa,
	0x9e, 0x46, 0xad, 0x85, 0x7c, 0xe8, 0xe2, 0x28, 0x12, 0x6a, 0xb2, 0x06, 0xfa, 0x33, 0x2a, 0x13,
	0xfd, 0x08, 0xfd, 0x98, 0xa7, 0x77, 0x4c, 0x16, 0x11, 0xf5, 0x87, 0x63, 0x67, 0xe2, 0x84, 0x2b,
	0x40, 0x8d, 0x70, 0x8c, 0xa5, 0x71, 0x6e, 0x6b, 0xe7, 0xd2, 0x56, 0x8d, 0x4a, 0x70, 0x36, 0x67,
	0x09, 0xbe, 0xa3, 0xfe, 0x8e, 0xee, 0x6e, 0x2f, 0xc1, 0xd9, 0xb9, 0xb2, 0x95, 0xf3, 0x16, 0x0b,
	0xeb, 0xdc, 0x35, 0xce, 0x5b, 0x2c, 0x8c, 0xf3, 0x10, 0x5c, 0x12, 0xf3, 0x9c, 0x5a, 0x37, 0xd2,
	0x6e, 0xd0, 0x90, 0x21, 0x1c, 0x55, 0xdb, 0xcc, 0x32, 0xf6, 0x34, 0xc3, 0xb5, 0x63, 0xa0, 0xa0,
	0xe0, 0x77, 0x70, 0xab, 0xb9, 0xb1, 0x6f, 0x57, 0x50, 0xc2, 0x45, 0xb4, 0xf9, 0x76, 0x0d, 0x5a,
	0xbd, 0xdd, 0xd7, 0xd0, 0x9b, 0xc5, 0xf8, 0x9e, 0x5e, 0x70, 0xa2, 0x14, 0xcd, 0x97, 0x6f, 0x56,
	0x1d, 0xd7, 0xb5, 0x68, 0x7c, 0x4d, 0x8b, 0xe6, 0xba, 0x16, 0xc1, 0x29, 0xb8, 0xff, 0xe3, 0x5c,
	0x52, 0xf1, 0x4a, 0x44, 0x54, 0xa8, 0xd4, 0xc9, 0x2a, 0x75, 0xc2, 0x22, 0x75, 0xa3, 0x44, 0x13,
	0xe6, 0x5c, 0x31, 0xec, 0xf4, 0xba, 0xc9, 0x2a, 0xe8, 0xd7, 0xcf, 0x4d, 0xe8, 0x98, 0x2b, 0xa1,
	0x33, 0x40, 0xe1, 0x82, 0xa5, 0x7c, 0xaa, 0x17, 0x8f, 0x5d, 0x52, 0xe8, 0xe0, 0xc4, 0xae, 0xf8,
	0xf5, 0x85, 0x3e, 0xda, 0x7f, 0x80, 0x67, 0x71, 0x19, 0x6c, 0xa1, 0xbf, 0x01, 0x74, 0x16, 0xbd,
	0x67, 0xd0, 0x92, 0x55, 0x5f, 0x5e, 0x23, 0xb4, 0x81, 0x9a, 0xc8, 0x29, 0xec, 0xfe, 0x87, 0x05,
	0x7d, 0x59, 0xf9, 0xbf, 0xa0, 0xaf, 0x92, 0x7c, 0x7b, 0xf5, 0x7f, 0xc0, 0x0b, 0x75, 0xd7, 0xac,
	0x1a, 0xdf, 0x55, 0xac, 0xb5, 0x45, 0x31, 0xda, 0xdb, 0x84, 0x4d, 0xf4, 0x9f, 0xe0, 0xea, 0x16,
	0xcf, 0x8a, 0x9b, 0x84, 0x49, 0xb4, 0x53, 0xb1, 0xaa, 0xbe, 0xaf, 0xe2, 0x6a, 0x1d, 0xd3, 0x55,
	0x07, 0x06, 0x08, 0x29, 0xa1, 0xec, 0x9e, 0xa2, 0xc7, 0x78, 0xa3, 0x07, 0xe9, 0x82, 0xad, 0x89,
	0xf3, 0x8b, 0x73, 0x3a, 0x86, 0x6d, 0xc6, 0x4f, 0xc8, 0x82, 0xbd, 0x67, 0x96, 0x71, 0x6a, 0xe7,
	0xf3, 0x4a, 0xfd, 0x8f, 0xaf, 0x9c, 0x9b, 0x8e, 0xfe, 0x31, 0xff, 0xf6, 0x25, 0x00, 0x00, 0xff,
	0xff, 0xf6, 0xf2, 0x5d, 0x27, 0xa8, 0x07, 0x00, 0x00,
}
